var annotated_dup =
[
    [ "Aimbot", "d8/d9a/classAimbot.html", "d8/d9a/classAimbot" ],
    [ "AimConfig", "dc/d76/classAimConfig.html", "dc/d76/classAimConfig" ],
    [ "AimService", "df/d6c/classAimService.html", "df/d6c/classAimService" ],
    [ "Builder", "d2/d59/classBuilder.html", "d2/d59/classBuilder" ],
    [ "CComponent", "d4/da1/classCComponent.html", "d4/da1/classCComponent" ],
    [ "Cheat", "d3/d59/classCheat.html", "d3/d59/classCheat" ],
    [ "Esp", "d1/d71/classEsp.html", "d1/d71/classEsp" ],
    [ "EspConfig", "dd/d62/classEspConfig.html", "dd/d62/classEspConfig" ],
    [ "Game", "d9/d68/classGame.html", "d9/d68/classGame" ],
    [ "GameVariables", "d4/dfa/classGameVariables.html", "d4/dfa/classGameVariables" ],
    [ "Hotkey", "d5/dc3/structHotkey.html", "d5/dc3/structHotkey" ],
    [ "LuaService", "df/dc4/classLuaService.html", "df/dc4/classLuaService" ],
    [ "MemoryService", "df/d7b/classMemoryService.html", "df/d7b/classMemoryService" ],
    [ "Notification", "d2/dc5/classNotification.html", "d2/dc5/classNotification" ],
    [ "NotificationService", "da/d3a/classNotificationService.html", "da/d3a/classNotificationService" ],
    [ "QuickAction", "d5/dba/classQuickAction.html", "d5/dba/classQuickAction" ],
    [ "QuickActionButton", "dd/d07/classQuickActionButton.html", "dd/d07/classQuickActionButton" ],
    [ "QuickActionCheckbox", "d8/d1e/classQuickActionCheckbox.html", "d8/d1e/classQuickActionCheckbox" ],
    [ "QuickActions", "d6/d31/classQuickActions.html", "d6/d31/classQuickActions" ],
    [ "QuickActionSlider", "d3/d1c/classQuickActionSlider.html", "d3/d1c/classQuickActionSlider" ],
    [ "Radar", "d3/d24/classRadar.html", "d3/d24/classRadar" ],
    [ "RadarConfig", "df/d07/classRadarConfig.html", "df/d07/classRadarConfig" ],
    [ "System", "dd/d2d/classSystem.html", "dd/d2d/classSystem" ],
    [ "TargetProfile", "db/d59/classTargetProfile.html", "db/d59/classTargetProfile" ],
    [ "UIConfig", "d5/de1/classUIConfig.html", "d5/de1/classUIConfig" ],
    [ "UIService", "da/da8/classUIService.html", "da/da8/classUIService" ],
    [ "Vec2", "d3/d95/classVec2.html", "d3/d95/classVec2" ],
    [ "Vec3", "d9/de4/classVec3.html", "d9/de4/classVec3" ],
    [ "Waypoint", "d9/d8c/classWaypoint.html", "d9/d8c/classWaypoint" ],
    [ "Waypoints", "d5/d11/classWaypoints.html", "d5/d11/classWaypoints" ],
    [ "WaypointsConfig", "d9/d7b/classWaypointsConfig.html", "d9/d7b/classWaypointsConfig" ],
    [ "Xenon", "de/dba/classXenon.html", "de/dba/classXenon" ],
    [ "XenonConfig", "d8/dd1/classXenonConfig.html", "d8/dd1/classXenonConfig" ],
    [ "XenonVariables", "d4/d79/classXenonVariables.html", "d4/d79/classXenonVariables" ]
];