#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_105061_BP

#include "Basic.hpp"

#include "PyAbility_105061_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_105061_BP.Ability_105061_BP_C
// 0x0000 (0x2580 - 0x2580)
class UAbility_105061_BP_C final : public UPyAbility_105061
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_105061_BP_C">();
	}
	static class UAbility_105061_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_105061_BP_C>();
	}
};
////static_assert(alignof(UAbility_105061_BP_C) == 0x000008, "Wrong alignment on UAbility_105061_BP_C");
////static_assert(sizeof(UAbility_105061_BP_C) == 0x002580, "Wrong size on UAbility_105061_BP_C");

}

