#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AeroLocomotionV2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AeroLocomotionV2_structs.hpp"
#include "AnimationPro_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "Marvel_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AeroLocomotionV2.AeroLocomotionV2_C
// 0x9520 (0xA4E0 - 0x0FC0)
class UAeroLocomotionV2_C final : public UAeroLocoMotionSubAnimInstanceV2
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0FC0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct AeroLocomotionV2::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                           // 0x0FC8(0x0088)(HasGetValueTypeHash)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x1050(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x1058(0x0008)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_10;                   // 0x1060(0x00A0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_9;                    // 0x1100(0x00A0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_8;                    // 0x11A0(0x00A0)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_27;  // 0x1240(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_63;                      // 0x1370(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_14;                     // 0x13A8(0x02A0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_7;                    // 0x1648(0x00A0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_6;                    // 0x16E8(0x00A0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_5;                    // 0x1788(0x00A0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_80;                 // 0x1828(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_79;                 // 0x1868(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_78;                 // 0x18A8(0x0040)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_26;  // 0x18E8(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_62;                      // 0x1A18(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_25;  // 0x1A50(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_61;                      // 0x1B80(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_24;  // 0x1BB8(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_60;                      // 0x1CE8(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_59;                      // 0x1D20(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_13;                     // 0x1D58(0x02A0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_4;                    // 0x1FF8(0x00A0)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_23;  // 0x2098(0x0130)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x21C8(0x00E0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_3;                    // 0x22A8(0x00A0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_2;                    // 0x2348(0x00A0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_77;                 // 0x23E8(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_76;                 // 0x2428(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_75;                 // 0x2468(0x0040)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_22;  // 0x24A8(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_58;                      // 0x25D8(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_21;  // 0x2610(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_57;                      // 0x2740(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_20;  // 0x2778(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_56;                      // 0x28A8(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_55;                      // 0x28E0(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_12;                     // 0x2918(0x02A0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1;                    // 0x2BB8(0x00A0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_74;                 // 0x2C58(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_73;                 // 0x2C98(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_72;                 // 0x2CD8(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_71;                 // 0x2D18(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_70;                 // 0x2D58(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_69;                 // 0x2D98(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_68;                 // 0x2DD8(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_67;                 // 0x2E18(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_66;                 // 0x2E58(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_65;                 // 0x2E98(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_64;                 // 0x2ED8(0x0040)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_1;                  // 0x2F18(0x0090)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_3;                   // 0x2FA8(0x0078)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x3020(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_54;                      // 0x30B0(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_19;  // 0x30E8(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_53;                      // 0x3218(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_18;  // 0x3250(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_52;                      // 0x3380(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_17;  // 0x33B8(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_51;                      // 0x34E8(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_16;  // 0x3520(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_50;                      // 0x3650(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_15;  // 0x3688(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_49;                      // 0x37B8(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_63;                 // 0x37F0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_62;                 // 0x3830(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_48;                      // 0x3870(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_17;                    // 0x38A8(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_47;                      // 0x38F0(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_61;                 // 0x3928(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_60;                 // 0x3968(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_59;                 // 0x39A8(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_58;                 // 0x39E8(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_57;                 // 0x3A28(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_56;                 // 0x3A68(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_55;                 // 0x3AA8(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_54;                 // 0x3AE8(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_53;                 // 0x3B28(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_52;                 // 0x3B68(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_51;                 // 0x3BA8(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_50;                 // 0x3BE8(0x0040)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_14;  // 0x3C28(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_46;                      // 0x3D58(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_45;                      // 0x3D90(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_49;                 // 0x3DC8(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_48;                 // 0x3E08(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_47;                 // 0x3E48(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_46;                 // 0x3E88(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_45;                 // 0x3EC8(0x0040)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_16;                    // 0x3F08(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_44;                      // 0x3F50(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_15;                    // 0x3F88(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_43;                      // 0x3FD0(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_13;  // 0x4008(0x0130)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_14;                    // 0x4138(0x0048)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_9;                     // 0x4180(0x00E8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_42;                      // 0x4268(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_12;  // 0x42A0(0x0130)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_13;                    // 0x43D0(0x0048)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_8;                     // 0x4418(0x00E8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_41;                      // 0x4500(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_11;                     // 0x4538(0x02A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_40;                      // 0x47D8(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_12;                    // 0x4810(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_39;                      // 0x4858(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_10;                     // 0x4890(0x02A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_38;                      // 0x4B30(0x0038)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_17;    // 0x4B68(0x00A0)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_16;    // 0x4C08(0x00A0)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_5;                       // 0x4CA8(0x00E0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_11;                    // 0x4D88(0x0048)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_7;                     // 0x4DD0(0x00E8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_37;                      // 0x4EB8(0x0038)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_15;    // 0x4EF0(0x00A0)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_14;    // 0x4F90(0x00A0)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_4;                       // 0x5030(0x00E0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_10;                    // 0x5110(0x0048)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_6;                     // 0x5158(0x00E8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_36;                      // 0x5240(0x0038)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_13;    // 0x5278(0x00A0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_9;                     // 0x5318(0x0048)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_5;                     // 0x5360(0x00E8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_35;                      // 0x5448(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_9;                      // 0x5480(0x02A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_34;                      // 0x5720(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_8;                      // 0x5758(0x02A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_33;                      // 0x59F8(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_44;                 // 0x5A30(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_43;                 // 0x5A70(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_42;                 // 0x5AB0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_41;                 // 0x5AF0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_40;                 // 0x5B30(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_39;                 // 0x5B70(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_38;                 // 0x5BB0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_37;                 // 0x5BF0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_36;                 // 0x5C30(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_35;                 // 0x5C70(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_34;                 // 0x5CB0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_33;                 // 0x5CF0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_32;                 // 0x5D30(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_31;                 // 0x5D70(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_30;                 // 0x5DB0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_29;                 // 0x5DF0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_28;                 // 0x5E30(0x0040)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_11;  // 0x5E70(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_32;                      // 0x5FA0(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_10;  // 0x5FD8(0x0130)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_12;    // 0x6108(0x00A0)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_11;    // 0x61A8(0x00A0)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_4;                     // 0x6248(0x00E8)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_2;                   // 0x6330(0x0078)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_31;                      // 0x63A8(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_27;                 // 0x63E0(0x0040)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_9;   // 0x6420(0x0130)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_10;    // 0x6550(0x00A0)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_9;     // 0x65F0(0x00A0)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_3;                     // 0x6690(0x00E8)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_1;                   // 0x6778(0x0078)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_30;                      // 0x67F0(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_8;   // 0x6828(0x0130)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_8;     // 0x6958(0x00A0)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_7;     // 0x69F8(0x00A0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x6A98(0x0078)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_2;                     // 0x6B10(0x00E8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_29;                      // 0x6BF8(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_26;                 // 0x6C30(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_25;                 // 0x6C70(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_24;                 // 0x6CB0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_23;                 // 0x6CF0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_22;                 // 0x6D30(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21;                 // 0x6D70(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20;                 // 0x6DB0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19;                 // 0x6DF0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18;                 // 0x6E30(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17;                 // 0x6E70(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16;                 // 0x6EB0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15;                 // 0x6EF0(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_28;                      // 0x6F30(0x0038)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_6;     // 0x6F68(0x00A0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_8;                     // 0x7008(0x0048)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_3;                       // 0x7050(0x00E0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_27;                      // 0x7130(0x0038)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_5;     // 0x7168(0x00A0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_7;                     // 0x7208(0x0048)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_2;                       // 0x7250(0x00E0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_26;                      // 0x7330(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_7;                      // 0x7368(0x02A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_25;                      // 0x7608(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14;                 // 0x7640(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13;                 // 0x7680(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_24;                      // 0x76C0(0x0038)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_4;     // 0x76F8(0x00A0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_6;                     // 0x7798(0x0048)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_1;                       // 0x77E0(0x00E0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_23;                      // 0x78C0(0x0038)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_3;     // 0x78F8(0x00A0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_5;                     // 0x7998(0x0048)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x79E0(0x00E0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_22;                      // 0x7AC0(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_6;                      // 0x7AF8(0x02A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_21;                      // 0x7D98(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_4;                     // 0x7DD0(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_20;                      // 0x7E18(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3;                     // 0x7E50(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_19;                      // 0x7E98(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_7;   // 0x7ED0(0x0130)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2;                     // 0x8000(0x0048)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_1;                     // 0x8048(0x00E8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_18;                      // 0x8130(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_6;   // 0x8168(0x0130)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x8298(0x0048)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive;                       // 0x82E0(0x00E8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_17;                      // 0x83C8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_5;                      // 0x8400(0x02A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_16;                      // 0x86A0(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x86D8(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_15;                      // 0x8720(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_4;                      // 0x8758(0x02A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_14;                      // 0x89F8(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x8A30(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x8A70(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x8AB0(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13;                      // 0x8AF0(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_5;   // 0x8B28(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12;                      // 0x8C58(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_4;   // 0x8C90(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11;                      // 0x8DC0(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_3;                      // 0x8DF8(0x02A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10;                      // 0x9098(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x90D0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x9110(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x9150(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9;                       // 0x9190(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_3;   // 0x91C8(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8;                       // 0x92F8(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_2;   // 0x9330(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7;                       // 0x9460(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_2;                      // 0x9498(0x02A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0x9738(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x9770(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0x97A8(0x02A0)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend_1;   // 0x9A48(0x0130)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x9B78(0x00A0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x9C18(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x9C58(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x9C98(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x9CD8(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x9D18(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x9D58(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x9D98(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x9DD8(0x0038)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_2;     // 0x9E10(0x00A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x9EB0(0x0038)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend_1;     // 0x9EE8(0x00A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x9F88(0x0038)()
	struct FMarvelAnimNode_BlendSpacePlayerWithBlend MarvelAnimGraphNode_BlendSpacePlayerWithBlend;     // 0x9FC0(0x0130)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0xA0F0(0x0038)()
	struct FMarvelAnimNode_SequencePlayerWithBlend MarvelAnimGraphNode_SequencePlayerWithBlend;       // 0xA128(0x00A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0xA1C8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0xA200(0x02A0)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0xA4A0(0x0038)()

public:
	void ExecuteUbergraph_AeroLocomotionV2(int32 EntryPoint);
	void AnimGraph(const struct FPoseLink& InGroundMotionPose, struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AeroLocomotionV2_C">();
	}
	static class UAeroLocomotionV2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAeroLocomotionV2_C>();
	}
};
//static_assert(alignof(UAeroLocomotionV2_C) == 0x000010, "Wrong alignment on UAeroLocomotionV2_C");
//static_assert(sizeof(UAeroLocomotionV2_C) == 0x00A4E0, "Wrong size on UAeroLocomotionV2_C");
//static_assert(offsetof(UAeroLocomotionV2_C, UberGraphFrame) == 0x000FC0, "Member 'UAeroLocomotionV2_C::UberGraphFrame' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, __AnimBlueprintMutables) == 0x000FC8, "Member 'UAeroLocomotionV2_C::__AnimBlueprintMutables' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimBlueprintExtension_PropertyAccess) == 0x001050, "Member 'UAeroLocomotionV2_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimBlueprintExtension_Base) == 0x001058, "Member 'UAeroLocomotionV2_C::AnimBlueprintExtension_Base' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_SaveCachedPose_10) == 0x001060, "Member 'UAeroLocomotionV2_C::AnimGraphNode_SaveCachedPose_10' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_SaveCachedPose_9) == 0x001100, "Member 'UAeroLocomotionV2_C::AnimGraphNode_SaveCachedPose_9' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_SaveCachedPose_8) == 0x0011A0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_SaveCachedPose_8' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_27) == 0x001240, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_27' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_63) == 0x001370, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_63' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine_14) == 0x0013A8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine_14' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_SaveCachedPose_7) == 0x001648, "Member 'UAeroLocomotionV2_C::AnimGraphNode_SaveCachedPose_7' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_SaveCachedPose_6) == 0x0016E8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_SaveCachedPose_6' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_SaveCachedPose_5) == 0x001788, "Member 'UAeroLocomotionV2_C::AnimGraphNode_SaveCachedPose_5' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_80) == 0x001828, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_80' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_79) == 0x001868, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_79' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_78) == 0x0018A8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_78' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_26) == 0x0018E8, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_26' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_62) == 0x001A18, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_62' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_25) == 0x001A50, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_25' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_61) == 0x001B80, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_61' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_24) == 0x001BB8, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_24' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_60) == 0x001CE8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_60' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_59) == 0x001D20, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_59' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine_13) == 0x001D58, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine_13' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_SaveCachedPose_4) == 0x001FF8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_SaveCachedPose_4' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_23) == 0x002098, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_23' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_LinkedInputPose) == 0x0021C8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_SaveCachedPose_3) == 0x0022A8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_SaveCachedPose_3' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_SaveCachedPose_2) == 0x002348, "Member 'UAeroLocomotionV2_C::AnimGraphNode_SaveCachedPose_2' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_77) == 0x0023E8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_77' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_76) == 0x002428, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_76' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_75) == 0x002468, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_75' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_22) == 0x0024A8, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_22' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_58) == 0x0025D8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_58' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_21) == 0x002610, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_21' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_57) == 0x002740, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_57' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_20) == 0x002778, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_20' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_56) == 0x0028A8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_56' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_55) == 0x0028E0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_55' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine_12) == 0x002918, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine_12' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_SaveCachedPose_1) == 0x002BB8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_SaveCachedPose_1' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_74) == 0x002C58, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_74' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_73) == 0x002C98, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_73' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_72) == 0x002CD8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_72' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_71) == 0x002D18, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_71' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_70) == 0x002D58, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_70' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_69) == 0x002D98, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_69' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_68) == 0x002DD8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_68' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_67) == 0x002E18, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_67' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_66) == 0x002E58, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_66' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_65) == 0x002E98, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_65' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_64) == 0x002ED8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_64' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_BlendSpacePlayer_1) == 0x002F18, "Member 'UAeroLocomotionV2_C::AnimGraphNode_BlendSpacePlayer_1' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_BlendListByBool_3) == 0x002FA8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_BlendListByBool_3' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_BlendSpacePlayer) == 0x003020, "Member 'UAeroLocomotionV2_C::AnimGraphNode_BlendSpacePlayer' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_54) == 0x0030B0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_54' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_19) == 0x0030E8, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_19' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_53) == 0x003218, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_53' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_18) == 0x003250, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_18' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_52) == 0x003380, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_52' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_17) == 0x0033B8, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_17' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_51) == 0x0034E8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_51' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_16) == 0x003520, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_16' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_50) == 0x003650, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_50' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_15) == 0x003688, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_15' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_49) == 0x0037B8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_49' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_63) == 0x0037F0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_63' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_62) == 0x003830, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_62' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_48) == 0x003870, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_48' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_17) == 0x0038A8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_17' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_47) == 0x0038F0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_47' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_61) == 0x003928, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_61' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_60) == 0x003968, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_60' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_59) == 0x0039A8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_59' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_58) == 0x0039E8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_58' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_57) == 0x003A28, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_57' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_56) == 0x003A68, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_56' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_55) == 0x003AA8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_55' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_54) == 0x003AE8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_54' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_53) == 0x003B28, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_53' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_52) == 0x003B68, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_52' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_51) == 0x003BA8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_51' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_50) == 0x003BE8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_50' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_14) == 0x003C28, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_14' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_46) == 0x003D58, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_46' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_45) == 0x003D90, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_45' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_49) == 0x003DC8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_49' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_48) == 0x003E08, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_48' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_47) == 0x003E48, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_47' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_46) == 0x003E88, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_46' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_45) == 0x003EC8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_45' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_16) == 0x003F08, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_16' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_44) == 0x003F50, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_44' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_15) == 0x003F88, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_15' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_43) == 0x003FD0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_43' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_13) == 0x004008, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_13' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_14) == 0x004138, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_14' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_ApplyAdditive_9) == 0x004180, "Member 'UAeroLocomotionV2_C::AnimGraphNode_ApplyAdditive_9' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_42) == 0x004268, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_42' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_12) == 0x0042A0, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_12' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_13) == 0x0043D0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_13' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_ApplyAdditive_8) == 0x004418, "Member 'UAeroLocomotionV2_C::AnimGraphNode_ApplyAdditive_8' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_41) == 0x004500, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_41' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine_11) == 0x004538, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine_11' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_40) == 0x0047D8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_40' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_12) == 0x004810, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_12' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_39) == 0x004858, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_39' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine_10) == 0x004890, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine_10' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_38) == 0x004B30, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_38' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_17) == 0x004B68, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_17' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_16) == 0x004C08, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_16' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TwoWayBlend_5) == 0x004CA8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TwoWayBlend_5' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_11) == 0x004D88, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_11' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_ApplyAdditive_7) == 0x004DD0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_ApplyAdditive_7' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_37) == 0x004EB8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_37' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_15) == 0x004EF0, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_15' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_14) == 0x004F90, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_14' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TwoWayBlend_4) == 0x005030, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TwoWayBlend_4' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_10) == 0x005110, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_10' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_ApplyAdditive_6) == 0x005158, "Member 'UAeroLocomotionV2_C::AnimGraphNode_ApplyAdditive_6' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_36) == 0x005240, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_36' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_13) == 0x005278, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_13' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_9) == 0x005318, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_9' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_ApplyAdditive_5) == 0x005360, "Member 'UAeroLocomotionV2_C::AnimGraphNode_ApplyAdditive_5' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_35) == 0x005448, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_35' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine_9) == 0x005480, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine_9' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_34) == 0x005720, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_34' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine_8) == 0x005758, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine_8' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_33) == 0x0059F8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_33' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_44) == 0x005A30, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_44' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_43) == 0x005A70, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_43' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_42) == 0x005AB0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_42' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_41) == 0x005AF0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_41' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_40) == 0x005B30, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_40' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_39) == 0x005B70, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_39' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_38) == 0x005BB0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_38' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_37) == 0x005BF0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_37' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_36) == 0x005C30, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_36' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_35) == 0x005C70, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_35' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_34) == 0x005CB0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_34' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_33) == 0x005CF0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_33' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_32) == 0x005D30, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_32' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_31) == 0x005D70, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_31' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_30) == 0x005DB0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_30' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_29) == 0x005DF0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_29' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_28) == 0x005E30, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_28' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_11) == 0x005E70, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_11' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_32) == 0x005FA0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_32' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_10) == 0x005FD8, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_10' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_12) == 0x006108, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_12' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_11) == 0x0061A8, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_11' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_ApplyAdditive_4) == 0x006248, "Member 'UAeroLocomotionV2_C::AnimGraphNode_ApplyAdditive_4' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_BlendListByBool_2) == 0x006330, "Member 'UAeroLocomotionV2_C::AnimGraphNode_BlendListByBool_2' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_31) == 0x0063A8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_31' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_27) == 0x0063E0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_27' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_9) == 0x006420, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_9' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_10) == 0x006550, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_10' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_9) == 0x0065F0, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_9' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_ApplyAdditive_3) == 0x006690, "Member 'UAeroLocomotionV2_C::AnimGraphNode_ApplyAdditive_3' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_BlendListByBool_1) == 0x006778, "Member 'UAeroLocomotionV2_C::AnimGraphNode_BlendListByBool_1' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_30) == 0x0067F0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_30' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_8) == 0x006828, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_8' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_8) == 0x006958, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_8' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_7) == 0x0069F8, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_7' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_BlendListByBool) == 0x006A98, "Member 'UAeroLocomotionV2_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_ApplyAdditive_2) == 0x006B10, "Member 'UAeroLocomotionV2_C::AnimGraphNode_ApplyAdditive_2' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_29) == 0x006BF8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_29' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_26) == 0x006C30, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_26' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_25) == 0x006C70, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_25' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_24) == 0x006CB0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_24' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_23) == 0x006CF0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_23' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_22) == 0x006D30, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_22' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_21) == 0x006D70, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_21' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_20) == 0x006DB0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_20' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_19) == 0x006DF0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_19' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_18) == 0x006E30, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_18' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_17) == 0x006E70, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_17' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_16) == 0x006EB0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_16' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_15) == 0x006EF0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_15' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_28) == 0x006F30, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_28' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_6) == 0x006F68, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_6' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_8) == 0x007008, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_8' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TwoWayBlend_3) == 0x007050, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TwoWayBlend_3' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_27) == 0x007130, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_27' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_5) == 0x007168, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_5' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_7) == 0x007208, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_7' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TwoWayBlend_2) == 0x007250, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TwoWayBlend_2' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_26) == 0x007330, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_26' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine_7) == 0x007368, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine_7' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_25) == 0x007608, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_25' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_14) == 0x007640, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_14' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_13) == 0x007680, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_13' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_24) == 0x0076C0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_24' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_4) == 0x0076F8, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_4' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_6) == 0x007798, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_6' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TwoWayBlend_1) == 0x0077E0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TwoWayBlend_1' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_23) == 0x0078C0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_23' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_3) == 0x0078F8, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_3' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_5) == 0x007998, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_5' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TwoWayBlend) == 0x0079E0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TwoWayBlend' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_22) == 0x007AC0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_22' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine_6) == 0x007AF8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine_6' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_21) == 0x007D98, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_21' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_4) == 0x007DD0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_4' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_20) == 0x007E18, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_20' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_3) == 0x007E50, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_3' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_19) == 0x007E98, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_19' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_7) == 0x007ED0, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_7' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_2) == 0x008000, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_2' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_ApplyAdditive_1) == 0x008048, "Member 'UAeroLocomotionV2_C::AnimGraphNode_ApplyAdditive_1' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_18) == 0x008130, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_18' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_6) == 0x008168, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_6' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose_1) == 0x008298, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_ApplyAdditive) == 0x0082E0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_ApplyAdditive' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_17) == 0x0083C8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_17' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine_5) == 0x008400, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine_5' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_16) == 0x0086A0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_16' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_UseCachedPose) == 0x0086D8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_15) == 0x008720, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_15' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine_4) == 0x008758, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine_4' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_14) == 0x0089F8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_14' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_12) == 0x008A30, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_12' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_11) == 0x008A70, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_11' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_10) == 0x008AB0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_10' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_13) == 0x008AF0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_13' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_5) == 0x008B28, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_5' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_12) == 0x008C58, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_12' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_4) == 0x008C90, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_4' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_11) == 0x008DC0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_11' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine_3) == 0x008DF8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine_3' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_10) == 0x009098, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_10' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_9) == 0x0090D0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_9' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_8) == 0x009110, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_8' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_7) == 0x009150, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_7' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_9) == 0x009190, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_9' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_3) == 0x0091C8, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_3' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_8) == 0x0092F8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_8' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_2) == 0x009330, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_2' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_7) == 0x009460, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_7' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine_2) == 0x009498, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine_2' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_6) == 0x009738, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_6' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_5) == 0x009770, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_5' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine_1) == 0x0097A8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine_1' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend_1) == 0x009A48, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend_1' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_SaveCachedPose) == 0x009B78, "Member 'UAeroLocomotionV2_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_6) == 0x009C18, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_6' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_5) == 0x009C58, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_4) == 0x009C98, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_3) == 0x009CD8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_2) == 0x009D18, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult_1) == 0x009D58, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_TransitionResult) == 0x009D98, "Member 'UAeroLocomotionV2_C::AnimGraphNode_TransitionResult' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_4) == 0x009DD8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_4' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_2) == 0x009E10, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_2' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_3) == 0x009EB0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_3' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend_1) == 0x009EE8, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend_1' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_2) == 0x009F88, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_2' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_BlendSpacePlayerWithBlend) == 0x009FC0, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_BlendSpacePlayerWithBlend' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult_1) == 0x00A0F0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult_1' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, MarvelAnimGraphNode_SequencePlayerWithBlend) == 0x00A128, "Member 'UAeroLocomotionV2_C::MarvelAnimGraphNode_SequencePlayerWithBlend' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateResult) == 0x00A1C8, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateResult' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_StateMachine) == 0x00A200, "Member 'UAeroLocomotionV2_C::AnimGraphNode_StateMachine' has a wrong offset!");
//static_assert(offsetof(UAeroLocomotionV2_C, AnimGraphNode_Root) == 0x00A4A0, "Member 'UAeroLocomotionV2_C::AnimGraphNode_Root' has a wrong offset!");

}

