#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AI_ScoreModule_FromPortal_BP

#include "Basic.hpp"

#include "MarvelAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AI_ScoreModule_FromPortal_BP.AI_ScoreModule_FromPortal_BP_C
// 0x0000 (0x0048 - 0x0048)
class UAI_ScoreModule_FromPortal_BP_C final : public UAIScoreModule_FromPortal
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AI_ScoreModule_FromPortal_BP_C">();
	}
	static class UAI_ScoreModule_FromPortal_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAI_ScoreModule_FromPortal_BP_C>();
	}
};
//static_assert(alignof(UAI_ScoreModule_FromPortal_BP_C) == 0x000008, "Wrong alignment on UAI_ScoreModule_FromPortal_BP_C");
//static_assert(sizeof(UAI_ScoreModule_FromPortal_BP_C) == 0x000048, "Wrong size on UAI_ScoreModule_FromPortal_BP_C");

}

