#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Amb_Practicerange_Mew_Far

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Amb_Practicerange_Mew_Far.Amb_Practicerange_Mew_Far_C
// 0x0010 (0x04A0 - 0x0490)
class AAmb_Practicerange_Mew_Far_C final : public AActor
{
public:
	class UAmbientAudioComponent*                 AmbientAudio;                                      // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Amb_Practicerange_Mew_Far_C">();
	}
	static class AAmb_Practicerange_Mew_Far_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAmb_Practicerange_Mew_Far_C>();
	}
};
//static_assert(alignof(AAmb_Practicerange_Mew_Far_C) == 0x000008, "Wrong alignment on AAmb_Practicerange_Mew_Far_C");
//static_assert(sizeof(AAmb_Practicerange_Mew_Far_C) == 0x0004A0, "Wrong size on AAmb_Practicerange_Mew_Far_C");
//static_assert(offsetof(AAmb_Practicerange_Mew_Far_C, AmbientAudio) == 0x000490, "Member 'AAmb_Practicerange_Mew_Far_C::AmbientAudio' has a wrong offset!");
//static_assert(offsetof(AAmb_Practicerange_Mew_Far_C, DefaultSceneRoot) == 0x000498, "Member 'AAmb_Practicerange_Mew_Far_C::DefaultSceneRoot' has a wrong offset!");

}

