#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Tokyo_Car

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Tokyo_Car.BP_Tokyo_Car_C
// 0x0018 (0x04A8 - 0x0490)
class ABP_Tokyo_Car_C final : public AActor
{
public:
	class UNiagaraComponent*                      Niagara;                                           // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USplineComponent*                       Spline;                                            // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x04A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Tokyo_Car_C">();
	}
	static class ABP_Tokyo_Car_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Tokyo_Car_C>();
	}
};
//static_assert(alignof(ABP_Tokyo_Car_C) == 0x000008, "Wrong alignment on ABP_Tokyo_Car_C");
//static_assert(sizeof(ABP_Tokyo_Car_C) == 0x0004A8, "Wrong size on ABP_Tokyo_Car_C");
//static_assert(offsetof(ABP_Tokyo_Car_C, Niagara) == 0x000490, "Member 'ABP_Tokyo_Car_C::Niagara' has a wrong offset!");
//static_assert(offsetof(ABP_Tokyo_Car_C, Spline) == 0x000498, "Member 'ABP_Tokyo_Car_C::Spline' has a wrong offset!");
//static_assert(offsetof(ABP_Tokyo_Car_C, DefaultSceneRoot) == 0x0004A0, "Member 'ABP_Tokyo_Car_C::DefaultSceneRoot' has a wrong offset!");

}

