#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTS_UpdateMapID_BP

#include "Basic.hpp"

#include "MarvelAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTS_UpdateMapID_BP.BTS_UpdateMapID_BP_C
// 0x0000 (0x00A8 - 0x00A8)
class UBTS_UpdateMapID_BP_C final : public UBTS_UpdateMapID
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTS_UpdateMapID_BP_C">();
	}
	static class UBTS_UpdateMapID_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTS_UpdateMapID_BP_C>();
	}
};
////static_assert(alignof(UBTS_UpdateMapID_BP_C) == 0x000008, "Wrong alignment on UBTS_UpdateMapID_BP_C");
////static_assert(sizeof(UBTS_UpdateMapID_BP_C) == 0x0000A8, "Wrong size on UBTS_UpdateMapID_BP_C");

}

