#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cue_Scope_Loop_40163101_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Cue_Scope_Loop_40163101_BP.Cue_Scope_Loop_40163101_BP_C
// 0x0000 (0x0FE8 - 0x0FE8)
class ACue_Scope_Loop_40163101_BP_C final : public AMarvelCueNotify_Laser
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Cue_Scope_Loop_40163101_BP_C">();
	}
	static class ACue_Scope_Loop_40163101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Scope_Loop_40163101_BP_C>();
	}
};
static_assert(alignof(ACue_Scope_Loop_40163101_BP_C) == 0x000008, "Wrong alignment on ACue_Scope_Loop_40163101_BP_C");
static_assert(sizeof(ACue_Scope_Loop_40163101_BP_C) == 0x000FE8, "Wrong size on ACue_Scope_Loop_40163101_BP_C");

}

