#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cue_Ability_Loop_10345403_BP

#include "Basic.hpp"

#include "Cue_Ability_Loop_10345103_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Cue_Ability_Loop_10345403_BP.Cue_Ability_Loop_10345403_BP_C
// 0x0020 (0x10E0 - 0x10C0)
class ACue_Ability_Loop_10345403_BP_C final : public ACue_Ability_Loop_10345103_BP_C
{
public:
	class UNiagaraComponent*                      LoopNS_FloatFxGammaR;                              // 0x10C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      LoopNS_FloatFxGammaL;                              // 0x10C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      LoopNS_HandFxGammaR;                               // 0x10D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      LoopNS_HandFxGammaL;                               // 0x10D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Cue_Ability_Loop_10345403_BP_C">();
	}
	static class ACue_Ability_Loop_10345403_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Ability_Loop_10345403_BP_C>();
	}
};
static_assert(alignof(ACue_Ability_Loop_10345403_BP_C) == 0x000008, "Wrong alignment on ACue_Ability_Loop_10345403_BP_C");
static_assert(sizeof(ACue_Ability_Loop_10345403_BP_C) == 0x0010E0, "Wrong size on ACue_Ability_Loop_10345403_BP_C");
static_assert(offsetof(ACue_Ability_Loop_10345403_BP_C, LoopNS_FloatFxGammaR) == 0x0010C0, "Member 'ACue_Ability_Loop_10345403_BP_C::LoopNS_FloatFxGammaR' has a wrong offset!");
static_assert(offsetof(ACue_Ability_Loop_10345403_BP_C, LoopNS_FloatFxGammaL) == 0x0010C8, "Member 'ACue_Ability_Loop_10345403_BP_C::LoopNS_FloatFxGammaL' has a wrong offset!");
static_assert(offsetof(ACue_Ability_Loop_10345403_BP_C, LoopNS_HandFxGammaR) == 0x0010D0, "Member 'ACue_Ability_Loop_10345403_BP_C::LoopNS_HandFxGammaR' has a wrong offset!");
static_assert(offsetof(ACue_Ability_Loop_10345403_BP_C, LoopNS_HandFxGammaL) == 0x0010D8, "Member 'ACue_Ability_Loop_10345403_BP_C::LoopNS_HandFxGammaL' has a wrong offset!");

}

