#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cue_Ability_Loop_10311101_BP

#include "Basic.hpp"

#include "PyAbility_103111_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Cue_Ability_Loop_10311101_BP.Cue_Ability_Loop_10311101_BP_C
// 0x0008 (0x0E60 - 0x0E58)
class ACue_Ability_Loop_10311101_BP_C final : public APyCue_Ability_Loop_10311101
{
public:
	class UNiagaraComponent*                      NS_Loop;                                           // 0x0E58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Cue_Ability_Loop_10311101_BP_C">();
	}
	static class ACue_Ability_Loop_10311101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Ability_Loop_10311101_BP_C>();
	}
};
static_assert(alignof(ACue_Ability_Loop_10311101_BP_C) == 0x000008, "Wrong alignment on ACue_Ability_Loop_10311101_BP_C");
static_assert(sizeof(ACue_Ability_Loop_10311101_BP_C) == 0x000E60, "Wrong size on ACue_Ability_Loop_10311101_BP_C");
static_assert(offsetof(ACue_Ability_Loop_10311101_BP_C, NS_Loop) == 0x000E58, "Member 'ACue_Ability_Loop_10311101_BP_C::NS_Loop' has a wrong offset!");

}

