#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LevelSequenceActorBP

#include "Basic.hpp"

#include "PyLevelSequenceActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LevelSequenceActorBP.LevelSequenceActorBP_C
// 0x0010 (0x0508 - 0x04F8)
class ALevelSequenceActorBP_C final : public APyLevelSequenceActor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x04F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	double                                        InitDelay;                                         // 0x0500(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LevelSequenceActorBP_C">();
	}
	static class ALevelSequenceActorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALevelSequenceActorBP_C>();
	}
};
static_assert(alignof(ALevelSequenceActorBP_C) == 0x000008, "Wrong alignment on ALevelSequenceActorBP_C");
static_assert(sizeof(ALevelSequenceActorBP_C) == 0x000508, "Wrong size on ALevelSequenceActorBP_C");
static_assert(offsetof(ALevelSequenceActorBP_C, DefaultSceneRoot) == 0x0004F8, "Member 'ALevelSequenceActorBP_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(ALevelSequenceActorBP_C, InitDelay) == 0x000500, "Member 'ALevelSequenceActorBP_C::InitDelay' has a wrong offset!");

}

