#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MarvelReplaySpectatorControllerBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PyMarvelReplayController_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MarvelReplaySpectatorControllerBP.MarvelReplaySpectatorControllerBP_C
// 0x0010 (0x1228 - 0x1218)
class AMarvelReplaySpectatorControllerBP_C final : public APyMarvelReplayController
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1218(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPythonComponent*                       Wizcmd;                                            // 0x1220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void SendCmdToPython(const class FString& Command);
	void ExecuteUbergraph_MarvelReplaySpectatorControllerBP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MarvelReplaySpectatorControllerBP_C">();
	}
	static class AMarvelReplaySpectatorControllerBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMarvelReplaySpectatorControllerBP_C>();
	}
};
static_assert(alignof(AMarvelReplaySpectatorControllerBP_C) == 0x000008, "Wrong alignment on AMarvelReplaySpectatorControllerBP_C");
static_assert(sizeof(AMarvelReplaySpectatorControllerBP_C) == 0x001228, "Wrong size on AMarvelReplaySpectatorControllerBP_C");
static_assert(offsetof(AMarvelReplaySpectatorControllerBP_C, UberGraphFrame) == 0x001218, "Member 'AMarvelReplaySpectatorControllerBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AMarvelReplaySpectatorControllerBP_C, Wizcmd) == 0x001220, "Member 'AMarvelReplaySpectatorControllerBP_C::Wizcmd' has a wrong offset!");

}

