#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: One031001_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Hero_1031_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass 1031001_AnimBP.1031001_AnimBP_C
// 0x1360 (0x1CB0 - 0x0950)
class UOne031001_AnimBP_C final : public ULunaSnowAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0950(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0958(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0960(0x0008)()
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_SubInstance_2;                       // 0x0968(0x00D0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x0A38(0x00A0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x0AD8(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x0B18(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x0B58(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x0B98(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x0BD8(0x0040)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x0C18(0x0060)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0x0C78(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0CB0(0x0060)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x0D10(0x0160)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x0E70(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x0EB8(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x0EF0(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x0F30(0x0040)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x0F70(0x0040)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_2;                  // 0x0FB0(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x1040(0x0038)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_1;                  // 0x1078(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x1108(0x0038)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x1140(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x11D0(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0x1208(0x02A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x14A8(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x14E0(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x1528(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x1560(0x02A0)()
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_SubInstance_1;                       // 0x1800(0x00D0)()
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_LinkedAnimGraph_1;                   // 0x18D0(0x00D0)()
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_LinkedAnimGraph;                     // 0x19A0(0x00D0)()
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_SubInstance;                         // 0x1A70(0x00D0)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x1B40(0x0038)()
	bool                                          __CustomProperty_bIsBattling_B5E82D174624620F97EF8FADA16AFE9E; // 0x1B78(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __CustomProperty_bShouldUseAO_B5E82D174624620F97EF8FADA16AFE9E; // 0x1B79(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B7A[0x2];                                     // 0x1B7A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __CustomProperty_LocalHitAlpha_46B4E6F94A7ADF4C1E46F090A551B44F; // 0x1B7C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __CustomProperty_LightHitAlpha_46B4E6F94A7ADF4C1E46F090A551B44F; // 0x1B80(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __CustomProperty_MediumHitAlpha_46B4E6F94A7ADF4C1E46F090A551B44F; // 0x1B84(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __CustomProperty_SevereHitAlpha_46B4E6F94A7ADF4C1E46F090A551B44F; // 0x1B88(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __CustomProperty_bUseSimulateHit_46B4E6F94A7ADF4C1E46F090A551B44F; // 0x1B8C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B8D[0x3];                                     // 0x1B8D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRuntimeFloatCurve                     __CustomProperty_HitHeadSpringCurve_46B4E6F94A7ADF4C1E46F090A551B44F; // 0x1B90(0x0088)()
	struct FRuntimeFloatCurve                     __CustomProperty_HitBodySpringCurve_46B4E6F94A7ADF4C1E46F090A551B44F; // 0x1C18(0x0088)()
	bool                                          __CustomProperty_bUseSpringHit_46B4E6F94A7ADF4C1E46F090A551B44F; // 0x1CA0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EExternMontageBlendMode                       __CustomProperty_ExternMontageBlendMode_49ECF9C647B02AB0C6B048BE2542E84E; // 0x1CA1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __CustomProperty_bUseNewJump_076850C9448ED8BEBDEDDFAE8D348574; // 0x1CA2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __CustomProperty_bUseSixDirAnimData_076850C9448ED8BEBDEDDFAE8D348574; // 0x1CA3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_1031001_AnimBP(int32 EntryPoint);
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"1031001_AnimBP_C">();
	}
	static class UOne031001_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOne031001_AnimBP_C>();
	}
};
static_assert(alignof(UOne031001_AnimBP_C) == 0x000010, "Wrong alignment on UOne031001_AnimBP_C");
static_assert(sizeof(UOne031001_AnimBP_C) == 0x001CB0, "Wrong size on UOne031001_AnimBP_C");
static_assert(offsetof(UOne031001_AnimBP_C, UberGraphFrame) == 0x000950, "Member 'UOne031001_AnimBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimBlueprintExtension_PropertyAccess) == 0x000958, "Member 'UOne031001_AnimBP_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimBlueprintExtension_Base) == 0x000960, "Member 'UOne031001_AnimBP_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_SubInstance_2) == 0x000968, "Member 'UOne031001_AnimBP_C::AnimGraphNode_SubInstance_2' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_SaveCachedPose) == 0x000A38, "Member 'UOne031001_AnimBP_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_TransitionResult_7) == 0x000AD8, "Member 'UOne031001_AnimBP_C::AnimGraphNode_TransitionResult_7' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_TransitionResult_6) == 0x000B18, "Member 'UOne031001_AnimBP_C::AnimGraphNode_TransitionResult_6' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_TransitionResult_5) == 0x000B58, "Member 'UOne031001_AnimBP_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_TransitionResult_4) == 0x000B98, "Member 'UOne031001_AnimBP_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_TransitionResult_3) == 0x000BD8, "Member 'UOne031001_AnimBP_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_SequencePlayer_1) == 0x000C18, "Member 'UOne031001_AnimBP_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_StateResult_6) == 0x000C78, "Member 'UOne031001_AnimBP_C::AnimGraphNode_StateResult_6' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_SequencePlayer) == 0x000CB0, "Member 'UOne031001_AnimBP_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_LayeredBoneBlend) == 0x000D10, "Member 'UOne031001_AnimBP_C::AnimGraphNode_LayeredBoneBlend' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_UseCachedPose_1) == 0x000E70, "Member 'UOne031001_AnimBP_C::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_StateResult_5) == 0x000EB8, "Member 'UOne031001_AnimBP_C::AnimGraphNode_StateResult_5' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_TransitionResult_2) == 0x000EF0, "Member 'UOne031001_AnimBP_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_TransitionResult_1) == 0x000F30, "Member 'UOne031001_AnimBP_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_TransitionResult) == 0x000F70, "Member 'UOne031001_AnimBP_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_BlendSpacePlayer_2) == 0x000FB0, "Member 'UOne031001_AnimBP_C::AnimGraphNode_BlendSpacePlayer_2' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_StateResult_4) == 0x001040, "Member 'UOne031001_AnimBP_C::AnimGraphNode_StateResult_4' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_BlendSpacePlayer_1) == 0x001078, "Member 'UOne031001_AnimBP_C::AnimGraphNode_BlendSpacePlayer_1' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_StateResult_3) == 0x001108, "Member 'UOne031001_AnimBP_C::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_BlendSpacePlayer) == 0x001140, "Member 'UOne031001_AnimBP_C::AnimGraphNode_BlendSpacePlayer' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_StateResult_2) == 0x0011D0, "Member 'UOne031001_AnimBP_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_StateMachine_1) == 0x001208, "Member 'UOne031001_AnimBP_C::AnimGraphNode_StateMachine_1' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_StateResult_1) == 0x0014A8, "Member 'UOne031001_AnimBP_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_UseCachedPose) == 0x0014E0, "Member 'UOne031001_AnimBP_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_StateResult) == 0x001528, "Member 'UOne031001_AnimBP_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_StateMachine) == 0x001560, "Member 'UOne031001_AnimBP_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_SubInstance_1) == 0x001800, "Member 'UOne031001_AnimBP_C::AnimGraphNode_SubInstance_1' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_LinkedAnimGraph_1) == 0x0018D0, "Member 'UOne031001_AnimBP_C::AnimGraphNode_LinkedAnimGraph_1' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_LinkedAnimGraph) == 0x0019A0, "Member 'UOne031001_AnimBP_C::AnimGraphNode_LinkedAnimGraph' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_SubInstance) == 0x001A70, "Member 'UOne031001_AnimBP_C::AnimGraphNode_SubInstance' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, AnimGraphNode_Root) == 0x001B40, "Member 'UOne031001_AnimBP_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, __CustomProperty_bIsBattling_B5E82D174624620F97EF8FADA16AFE9E) == 0x001B78, "Member 'UOne031001_AnimBP_C::__CustomProperty_bIsBattling_B5E82D174624620F97EF8FADA16AFE9E' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, __CustomProperty_bShouldUseAO_B5E82D174624620F97EF8FADA16AFE9E) == 0x001B79, "Member 'UOne031001_AnimBP_C::__CustomProperty_bShouldUseAO_B5E82D174624620F97EF8FADA16AFE9E' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, __CustomProperty_LocalHitAlpha_46B4E6F94A7ADF4C1E46F090A551B44F) == 0x001B7C, "Member 'UOne031001_AnimBP_C::__CustomProperty_LocalHitAlpha_46B4E6F94A7ADF4C1E46F090A551B44F' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, __CustomProperty_LightHitAlpha_46B4E6F94A7ADF4C1E46F090A551B44F) == 0x001B80, "Member 'UOne031001_AnimBP_C::__CustomProperty_LightHitAlpha_46B4E6F94A7ADF4C1E46F090A551B44F' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, __CustomProperty_MediumHitAlpha_46B4E6F94A7ADF4C1E46F090A551B44F) == 0x001B84, "Member 'UOne031001_AnimBP_C::__CustomProperty_MediumHitAlpha_46B4E6F94A7ADF4C1E46F090A551B44F' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, __CustomProperty_SevereHitAlpha_46B4E6F94A7ADF4C1E46F090A551B44F) == 0x001B88, "Member 'UOne031001_AnimBP_C::__CustomProperty_SevereHitAlpha_46B4E6F94A7ADF4C1E46F090A551B44F' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, __CustomProperty_bUseSimulateHit_46B4E6F94A7ADF4C1E46F090A551B44F) == 0x001B8C, "Member 'UOne031001_AnimBP_C::__CustomProperty_bUseSimulateHit_46B4E6F94A7ADF4C1E46F090A551B44F' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, __CustomProperty_HitHeadSpringCurve_46B4E6F94A7ADF4C1E46F090A551B44F) == 0x001B90, "Member 'UOne031001_AnimBP_C::__CustomProperty_HitHeadSpringCurve_46B4E6F94A7ADF4C1E46F090A551B44F' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, __CustomProperty_HitBodySpringCurve_46B4E6F94A7ADF4C1E46F090A551B44F) == 0x001C18, "Member 'UOne031001_AnimBP_C::__CustomProperty_HitBodySpringCurve_46B4E6F94A7ADF4C1E46F090A551B44F' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, __CustomProperty_bUseSpringHit_46B4E6F94A7ADF4C1E46F090A551B44F) == 0x001CA0, "Member 'UOne031001_AnimBP_C::__CustomProperty_bUseSpringHit_46B4E6F94A7ADF4C1E46F090A551B44F' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, __CustomProperty_ExternMontageBlendMode_49ECF9C647B02AB0C6B048BE2542E84E) == 0x001CA1, "Member 'UOne031001_AnimBP_C::__CustomProperty_ExternMontageBlendMode_49ECF9C647B02AB0C6B048BE2542E84E' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, __CustomProperty_bUseNewJump_076850C9448ED8BEBDEDDFAE8D348574) == 0x001CA2, "Member 'UOne031001_AnimBP_C::__CustomProperty_bUseNewJump_076850C9448ED8BEBDEDDFAE8D348574' has a wrong offset!");
static_assert(offsetof(UOne031001_AnimBP_C, __CustomProperty_bUseSixDirAnimData_076850C9448ED8BEBDEDDFAE8D348574) == 0x001CA3, "Member 'UOne031001_AnimBP_C::__CustomProperty_bUseSixDirAnimData_076850C9448ED8BEBDEDDFAE8D348574' has a wrong offset!");

}

