#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_10503102_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Marvel_structs.hpp"
#include "PyAbility_105031_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Projectile_10503102_BP.Projectile_10503102_BP_C
// 0x03A0 (0x3420 - 0x3080)
class AProjectile_10503102_BP_C final : public APyProjectile_10503102
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x3080(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FMarvelTraceRule                       TraceEnemy;                                        // 0x3088(0x0390)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_Projectile_10503102_BP(int32 EntryPoint);
	void K2_OnPenetrate(const struct FHitResult& ImpactResult, const struct FVector& ImpactVelocity);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Projectile_10503102_BP_C">();
	}
	static class AProjectile_10503102_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile_10503102_BP_C>();
	}
};
static_assert(alignof(AProjectile_10503102_BP_C) == 0x000010, "Wrong alignment on AProjectile_10503102_BP_C");
static_assert(sizeof(AProjectile_10503102_BP_C) == 0x003420, "Wrong size on AProjectile_10503102_BP_C");
static_assert(offsetof(AProjectile_10503102_BP_C, UberGraphFrame) == 0x003080, "Member 'AProjectile_10503102_BP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AProjectile_10503102_BP_C, TraceEnemy) == 0x003088, "Member 'AProjectile_10503102_BP_C::TraceEnemy' has a wrong offset!");

}

