#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_10403201_BP

#include "Basic.hpp"

#include "Hero_1040_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Projectile_10403201_BP.Projectile_10403201_BP_C
// 0x0010 (0x3080 - 0x3070)
class AProjectile_10403201_BP_C final : public AProjectile_10403201
{
public:
	class UProjectileHomingComponent*             ProjectileHoming;                                  // 0x3070(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Projectile_10403201_BP_C">();
	}
	static class AProjectile_10403201_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile_10403201_BP_C>();
	}
};
static_assert(alignof(AProjectile_10403201_BP_C) == 0x000010, "Wrong alignment on AProjectile_10403201_BP_C");
static_assert(sizeof(AProjectile_10403201_BP_C) == 0x003080, "Wrong size on AProjectile_10403201_BP_C");
static_assert(offsetof(AProjectile_10403201_BP_C, ProjectileHoming) == 0x003070, "Member 'AProjectile_10403201_BP_C::ProjectileHoming' has a wrong offset!");

}

