#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_104001

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyAbility_104001.PyAbility_104001.OnTagUpdate
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_104001_OnTagUpdate final
{
public:
	struct FGameplayTag                           Tag;                                               // 0x0000(0x000C)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)
	bool                                          Exist;                                             // 0x000C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_104001_OnTagUpdate) == 0x000004, "Wrong alignment on PyAbility_104001_OnTagUpdate");
static_assert(sizeof(PyAbility_104001_OnTagUpdate) == 0x000010, "Wrong size on PyAbility_104001_OnTagUpdate");
static_assert(offsetof(PyAbility_104001_OnTagUpdate, Tag) == 0x000000, "Member 'PyAbility_104001_OnTagUpdate::Tag' has a wrong offset!");
static_assert(offsetof(PyAbility_104001_OnTagUpdate, Exist) == 0x00000C, "Member 'PyAbility_104001_OnTagUpdate::Exist' has a wrong offset!");

// PythonFunction PyAbility_104001.PyAbility_104001.OnOwnerDeath
// 0x0028 (0x0028 - 0x0000)
struct PyAbility_104001_OnOwnerDeath final
{
public:
	class AActor*                                 InSource;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 InTarget;                                          // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FAttributeModifierHandle               ParamHandle;                                       // 0x0010(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_104001_OnOwnerDeath) == 0x000008, "Wrong alignment on PyAbility_104001_OnOwnerDeath");
static_assert(sizeof(PyAbility_104001_OnOwnerDeath) == 0x000028, "Wrong size on PyAbility_104001_OnOwnerDeath");
static_assert(offsetof(PyAbility_104001_OnOwnerDeath, InSource) == 0x000000, "Member 'PyAbility_104001_OnOwnerDeath::InSource' has a wrong offset!");
static_assert(offsetof(PyAbility_104001_OnOwnerDeath, InTarget) == 0x000008, "Member 'PyAbility_104001_OnOwnerDeath::InTarget' has a wrong offset!");
static_assert(offsetof(PyAbility_104001_OnOwnerDeath, ParamHandle) == 0x000010, "Member 'PyAbility_104001_OnOwnerDeath::ParamHandle' has a wrong offset!");

// PythonFunction PyAbility_104001.PyAbility_104001.CanActivate
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_104001_CanActivate final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_104001_CanActivate) == 0x000001, "Wrong alignment on PyAbility_104001_CanActivate");
static_assert(sizeof(PyAbility_104001_CanActivate) == 0x000001, "Wrong size on PyAbility_104001_CanActivate");
static_assert(offsetof(PyAbility_104001_CanActivate, ReturnValue) == 0x000000, "Member 'PyAbility_104001_CanActivate::ReturnValue' has a wrong offset!");

// PythonFunction PyAbility_104001.PyAbility_104001.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_104001_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_104001_K2_OnEndAbility) == 0x000001, "Wrong alignment on PyAbility_104001_K2_OnEndAbility");
static_assert(sizeof(PyAbility_104001_K2_OnEndAbility) == 0x000001, "Wrong size on PyAbility_104001_K2_OnEndAbility");
static_assert(offsetof(PyAbility_104001_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'PyAbility_104001_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

// PythonFunction PyAbility_104001.PyAbility_104001.NativeOnMontageCompleted
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_104001_NativeOnMontageCompleted final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_104001_NativeOnMontageCompleted) == 0x000008, "Wrong alignment on PyAbility_104001_NativeOnMontageCompleted");
static_assert(sizeof(PyAbility_104001_NativeOnMontageCompleted) == 0x000010, "Wrong size on PyAbility_104001_NativeOnMontageCompleted");
static_assert(offsetof(PyAbility_104001_NativeOnMontageCompleted, Tag) == 0x000000, "Member 'PyAbility_104001_NativeOnMontageCompleted::Tag' has a wrong offset!");

// PythonFunction PyAbility_104001.PyAbility_104001.NativeOnMontageBlendOut
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_104001_NativeOnMontageBlendOut final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_104001_NativeOnMontageBlendOut) == 0x000008, "Wrong alignment on PyAbility_104001_NativeOnMontageBlendOut");
static_assert(sizeof(PyAbility_104001_NativeOnMontageBlendOut) == 0x000010, "Wrong size on PyAbility_104001_NativeOnMontageBlendOut");
static_assert(offsetof(PyAbility_104001_NativeOnMontageBlendOut, Tag) == 0x000000, "Member 'PyAbility_104001_NativeOnMontageBlendOut::Tag' has a wrong offset!");

// PythonFunction PyAbility_104001.PyAbility_104001.NativeOnMontageInterrupted
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_104001_NativeOnMontageInterrupted final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_104001_NativeOnMontageInterrupted) == 0x000008, "Wrong alignment on PyAbility_104001_NativeOnMontageInterrupted");
static_assert(sizeof(PyAbility_104001_NativeOnMontageInterrupted) == 0x000010, "Wrong size on PyAbility_104001_NativeOnMontageInterrupted");
static_assert(offsetof(PyAbility_104001_NativeOnMontageInterrupted, Tag) == 0x000000, "Member 'PyAbility_104001_NativeOnMontageInterrupted::Tag' has a wrong offset!");

// PythonFunction PyAbility_104001.PyAbility_104001.NativeOnMontageCancelled
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_104001_NativeOnMontageCancelled final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_104001_NativeOnMontageCancelled) == 0x000008, "Wrong alignment on PyAbility_104001_NativeOnMontageCancelled");
static_assert(sizeof(PyAbility_104001_NativeOnMontageCancelled) == 0x000010, "Wrong size on PyAbility_104001_NativeOnMontageCancelled");
static_assert(offsetof(PyAbility_104001_NativeOnMontageCancelled, Tag) == 0x000000, "Member 'PyAbility_104001_NativeOnMontageCancelled::Tag' has a wrong offset!");

// PythonFunction PyAbility_104001.PyAbility_104001.NativeOnMontageEvent
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_104001_NativeOnMontageEvent final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_104001_NativeOnMontageEvent) == 0x000008, "Wrong alignment on PyAbility_104001_NativeOnMontageEvent");
static_assert(sizeof(PyAbility_104001_NativeOnMontageEvent) == 0x000010, "Wrong size on PyAbility_104001_NativeOnMontageEvent");
static_assert(offsetof(PyAbility_104001_NativeOnMontageEvent, Tag) == 0x000000, "Member 'PyAbility_104001_NativeOnMontageEvent::Tag' has a wrong offset!");

}

