#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_104991

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Hero_1049_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_104991.PyCue_Ability_Loop_10499101
// 0x0000 (0x0F80 - 0x0F80)
class APyCue_Ability_Loop_10499101 final : public ACue_Ability_Loop_10499101
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Ability_Loop_10499101">();
	}
	static class APyCue_Ability_Loop_10499101* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Ability_Loop_10499101>();
	}
};
static_assert(alignof(APyCue_Ability_Loop_10499101) == 0x000008, "Wrong alignment on APyCue_Ability_Loop_10499101");
static_assert(sizeof(APyCue_Ability_Loop_10499101) == 0x000F80, "Wrong size on APyCue_Ability_Loop_10499101");

// PythonClass PyAbility_104991.PyConfig_104991
// 0x0FB0 (0x3250 - 0x22A0)
class UPyConfig_104991 final : public UConfig_104991
{
public:
	struct FVector                                CapsuleLocationOffset;                             // 0x22A0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_22B8[0x8];                                     // 0x22B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMarvelAbilityTraceContext             TraceContext;                                      // 0x22C0(0x0F90)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyConfig_104991">();
	}
	static class UPyConfig_104991* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_104991>();
	}
};
static_assert(alignof(UPyConfig_104991) == 0x000010, "Wrong alignment on UPyConfig_104991");
static_assert(sizeof(UPyConfig_104991) == 0x003250, "Wrong size on UPyConfig_104991");
static_assert(offsetof(UPyConfig_104991, CapsuleLocationOffset) == 0x0022A0, "Member 'UPyConfig_104991::CapsuleLocationOffset' has a wrong offset!");
static_assert(offsetof(UPyConfig_104991, TraceContext) == 0x0022C0, "Member 'UPyConfig_104991::TraceContext' has a wrong offset!");

// PythonClass PyAbility_104991.PyAbility_104991
// 0x0000 (0x2DC8 - 0x2DC8)
class UPyAbility_104991 : public UAbility_104991
{
public:
	void BeginPlay();
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	void K2_OnWavingConfirmed();
	void Python_StartFlyingToHulk();
	void OnDashTaskFinish(EDashStopReason Reason);
	void Python_FailedFlyingToHulk();
	void Python_AttachToHulk();
	void Python_OnRideCancel();
	void OnHulkRepToSimulatedRole();
	void Python_DetachFromHulk();
	void K2_OnEndAbility(bool bWasCancelled);
	bool IsAbilityNormalEnd();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_104991">();
	}
	static class UPyAbility_104991* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_104991>();
	}
};
static_assert(alignof(UPyAbility_104991) == 0x000008, "Wrong alignment on UPyAbility_104991");
static_assert(sizeof(UPyAbility_104991) == 0x002DC8, "Wrong size on UPyAbility_104991");

}

