#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_105041

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyAbility_105041.PySummonedComp_10504101.K2_OnSummonedDeath
// 0x0028 (0x0028 - 0x0000)
struct PySummonedComp_10504101_K2_OnSummonedDeath final
{
public:
	class AActor*                                 InSourceAvatar;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 InTargetAvatar;                                    // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FAttributeModifierHandle               ModifierParameterHandle;                           // 0x0010(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
};
static_assert(alignof(PySummonedComp_10504101_K2_OnSummonedDeath) == 0x000008, "Wrong alignment on PySummonedComp_10504101_K2_OnSummonedDeath");
static_assert(sizeof(PySummonedComp_10504101_K2_OnSummonedDeath) == 0x000028, "Wrong size on PySummonedComp_10504101_K2_OnSummonedDeath");
static_assert(offsetof(PySummonedComp_10504101_K2_OnSummonedDeath, InSourceAvatar) == 0x000000, "Member 'PySummonedComp_10504101_K2_OnSummonedDeath::InSourceAvatar' has a wrong offset!");
static_assert(offsetof(PySummonedComp_10504101_K2_OnSummonedDeath, InTargetAvatar) == 0x000008, "Member 'PySummonedComp_10504101_K2_OnSummonedDeath::InTargetAvatar' has a wrong offset!");
static_assert(offsetof(PySummonedComp_10504101_K2_OnSummonedDeath, ModifierParameterHandle) == 0x000010, "Member 'PySummonedComp_10504101_K2_OnSummonedDeath::ModifierParameterHandle' has a wrong offset!");

// PythonFunction PyAbility_105041.PyAbility_105041.OnCharacterDeath
// 0x0028 (0x0028 - 0x0000)
struct PyAbility_105041_OnCharacterDeath final
{
public:
	class AActor*                                 InSourceAvatar;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 InTargetAvatar;                                    // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FAttributeModifierHandle               ModifierParameterHandle;                           // 0x0010(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105041_OnCharacterDeath) == 0x000008, "Wrong alignment on PyAbility_105041_OnCharacterDeath");
static_assert(sizeof(PyAbility_105041_OnCharacterDeath) == 0x000028, "Wrong size on PyAbility_105041_OnCharacterDeath");
static_assert(offsetof(PyAbility_105041_OnCharacterDeath, InSourceAvatar) == 0x000000, "Member 'PyAbility_105041_OnCharacterDeath::InSourceAvatar' has a wrong offset!");
static_assert(offsetof(PyAbility_105041_OnCharacterDeath, InTargetAvatar) == 0x000008, "Member 'PyAbility_105041_OnCharacterDeath::InTargetAvatar' has a wrong offset!");
static_assert(offsetof(PyAbility_105041_OnCharacterDeath, ModifierParameterHandle) == 0x000010, "Member 'PyAbility_105041_OnCharacterDeath::ModifierParameterHandle' has a wrong offset!");

// PythonFunction PyAbility_105041.PyAbility_105041.OnCharacterReborn
// 0x0740 (0x0740 - 0x0000)
struct PyAbility_105041_OnCharacterReborn final
{
public:
	class AActor*                                 TargetActor;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCharacterRebornParam                  Param;                                             // 0x0010(0x0730)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PyAbility_105041_OnCharacterReborn) == 0x000010, "Wrong alignment on PyAbility_105041_OnCharacterReborn");
static_assert(sizeof(PyAbility_105041_OnCharacterReborn) == 0x000740, "Wrong size on PyAbility_105041_OnCharacterReborn");
static_assert(offsetof(PyAbility_105041_OnCharacterReborn, TargetActor) == 0x000000, "Member 'PyAbility_105041_OnCharacterReborn::TargetActor' has a wrong offset!");
static_assert(offsetof(PyAbility_105041_OnCharacterReborn, Param) == 0x000010, "Member 'PyAbility_105041_OnCharacterReborn::Param' has a wrong offset!");

// PythonFunction PyAbility_105041.PyAbility_105041.InitShield
// 0x0008 (0x0008 - 0x0000)
struct PyAbility_105041_InitShield final
{
public:
	class AActor*                                 InActor;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105041_InitShield) == 0x000008, "Wrong alignment on PyAbility_105041_InitShield");
static_assert(sizeof(PyAbility_105041_InitShield) == 0x000008, "Wrong size on PyAbility_105041_InitShield");
static_assert(offsetof(PyAbility_105041_InitShield, InActor) == 0x000000, "Member 'PyAbility_105041_InitShield::InActor' has a wrong offset!");

// PythonFunction PyAbility_105041.PyAbility_105041.CanActivate
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_105041_CanActivate final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105041_CanActivate) == 0x000001, "Wrong alignment on PyAbility_105041_CanActivate");
static_assert(sizeof(PyAbility_105041_CanActivate) == 0x000001, "Wrong size on PyAbility_105041_CanActivate");
static_assert(offsetof(PyAbility_105041_CanActivate, ReturnValue) == 0x000000, "Member 'PyAbility_105041_CanActivate::ReturnValue' has a wrong offset!");

// PythonFunction PyAbility_105041.PyAbility_105041.HandleAbilityStageActions
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_105041_HandleAbilityStageActions final
{
public:
	EMarvelAbilityStage                           InStage;                                           // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105041_HandleAbilityStageActions) == 0x000001, "Wrong alignment on PyAbility_105041_HandleAbilityStageActions");
static_assert(sizeof(PyAbility_105041_HandleAbilityStageActions) == 0x000001, "Wrong size on PyAbility_105041_HandleAbilityStageActions");
static_assert(offsetof(PyAbility_105041_HandleAbilityStageActions, InStage) == 0x000000, "Member 'PyAbility_105041_HandleAbilityStageActions::InStage' has a wrong offset!");

// PythonFunction PyAbility_105041.PyAbility_105041.GetSelectTarget
// 0x0008 (0x0008 - 0x0000)
struct PyAbility_105041_GetSelectTarget final
{
public:
	class AActor*                                 ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105041_GetSelectTarget) == 0x000008, "Wrong alignment on PyAbility_105041_GetSelectTarget");
static_assert(sizeof(PyAbility_105041_GetSelectTarget) == 0x000008, "Wrong size on PyAbility_105041_GetSelectTarget");
static_assert(offsetof(PyAbility_105041_GetSelectTarget, ReturnValue) == 0x000000, "Member 'PyAbility_105041_GetSelectTarget::ReturnValue' has a wrong offset!");

// PythonFunction PyAbility_105041.PyAbility_105041.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_105041_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105041_K2_OnEndAbility) == 0x000001, "Wrong alignment on PyAbility_105041_K2_OnEndAbility");
static_assert(sizeof(PyAbility_105041_K2_OnEndAbility) == 0x000001, "Wrong size on PyAbility_105041_K2_OnEndAbility");
static_assert(offsetof(PyAbility_105041_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'PyAbility_105041_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

// PythonFunction PyAbility_105041.PySummoned_10504101.BarrierIsActive
// 0x0001 (0x0001 - 0x0000)
struct PySummoned_10504101_BarrierIsActive final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PySummoned_10504101_BarrierIsActive) == 0x000001, "Wrong alignment on PySummoned_10504101_BarrierIsActive");
static_assert(sizeof(PySummoned_10504101_BarrierIsActive) == 0x000001, "Wrong size on PySummoned_10504101_BarrierIsActive");
static_assert(offsetof(PySummoned_10504101_BarrierIsActive, ReturnValue) == 0x000000, "Member 'PySummoned_10504101_BarrierIsActive::ReturnValue' has a wrong offset!");

// DelegateFunction PyAbility_105041.PySummoned_10504101.OnBarrierTargetChange__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct PySummoned_10504101_OnBarrierTargetChange__DelegateSignature final
{
public:
	class AActor*                                 NewTarget;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PySummoned_10504101_OnBarrierTargetChange__DelegateSignature) == 0x000008, "Wrong alignment on PySummoned_10504101_OnBarrierTargetChange__DelegateSignature");
static_assert(sizeof(PySummoned_10504101_OnBarrierTargetChange__DelegateSignature) == 0x000008, "Wrong size on PySummoned_10504101_OnBarrierTargetChange__DelegateSignature");
static_assert(offsetof(PySummoned_10504101_OnBarrierTargetChange__DelegateSignature, NewTarget) == 0x000000, "Member 'PySummoned_10504101_OnBarrierTargetChange__DelegateSignature::NewTarget' has a wrong offset!");

// PythonFunction PyAbility_105041.PySummoned_10504101.update_barrier_target_and_location
// 0x0008 (0x0008 - 0x0000)
struct PySummoned_10504101_Update_barrier_target_and_location final
{
public:
	class AActor*                                 Target;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PySummoned_10504101_Update_barrier_target_and_location) == 0x000008, "Wrong alignment on PySummoned_10504101_Update_barrier_target_and_location");
static_assert(sizeof(PySummoned_10504101_Update_barrier_target_and_location) == 0x000008, "Wrong size on PySummoned_10504101_Update_barrier_target_and_location");
static_assert(offsetof(PySummoned_10504101_Update_barrier_target_and_location, Target) == 0x000000, "Member 'PySummoned_10504101_Update_barrier_target_and_location::Target' has a wrong offset!");

// PythonFunction PyAbility_105041.PySummoned_10504101.MulticastTargetChange
// 0x0008 (0x0008 - 0x0000)
struct PySummoned_10504101_MulticastTargetChange final
{
public:
	class AActor*                                 NewTarget;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PySummoned_10504101_MulticastTargetChange) == 0x000008, "Wrong alignment on PySummoned_10504101_MulticastTargetChange");
static_assert(sizeof(PySummoned_10504101_MulticastTargetChange) == 0x000008, "Wrong size on PySummoned_10504101_MulticastTargetChange");
static_assert(offsetof(PySummoned_10504101_MulticastTargetChange, NewTarget) == 0x000000, "Member 'PySummoned_10504101_MulticastTargetChange::NewTarget' has a wrong offset!");

// PythonFunction PyAbility_105041.PySummoned_10504101.OnHealingScopeSpawn
// 0x0170 (0x0170 - 0x0000)
struct PySummoned_10504101_OnHealingScopeSpawn final
{
public:
	class AActor*                                 SpawnActor;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       Data;                                              // 0x0008(0x0168)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PySummoned_10504101_OnHealingScopeSpawn) == 0x000008, "Wrong alignment on PySummoned_10504101_OnHealingScopeSpawn");
static_assert(sizeof(PySummoned_10504101_OnHealingScopeSpawn) == 0x000170, "Wrong size on PySummoned_10504101_OnHealingScopeSpawn");
static_assert(offsetof(PySummoned_10504101_OnHealingScopeSpawn, SpawnActor) == 0x000000, "Member 'PySummoned_10504101_OnHealingScopeSpawn::SpawnActor' has a wrong offset!");
static_assert(offsetof(PySummoned_10504101_OnHealingScopeSpawn, Data) == 0x000008, "Member 'PySummoned_10504101_OnHealingScopeSpawn::Data' has a wrong offset!");

// PythonFunction PyAbility_105041.PyCue_Summoner_Loop_10504101.WhileActiveAudio
// 0x01C0 (0x01C0 - 0x0000)
struct PyCue_Summoner_Loop_10504101_WhileActiveAudio final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PyCue_Summoner_Loop_10504101_WhileActiveAudio) == 0x000008, "Wrong alignment on PyCue_Summoner_Loop_10504101_WhileActiveAudio");
static_assert(sizeof(PyCue_Summoner_Loop_10504101_WhileActiveAudio) == 0x0001C0, "Wrong size on PyCue_Summoner_Loop_10504101_WhileActiveAudio");
static_assert(offsetof(PyCue_Summoner_Loop_10504101_WhileActiveAudio, MyTarget) == 0x000000, "Member 'PyCue_Summoner_Loop_10504101_WhileActiveAudio::MyTarget' has a wrong offset!");
static_assert(offsetof(PyCue_Summoner_Loop_10504101_WhileActiveAudio, Parameters) == 0x000008, "Member 'PyCue_Summoner_Loop_10504101_WhileActiveAudio::Parameters' has a wrong offset!");

// PythonFunction PyAbility_105041.PyCue_Summoner_Loop_10504101.OnExecuteAudio
// 0x01C0 (0x01C0 - 0x0000)
struct PyCue_Summoner_Loop_10504101_OnExecuteAudio final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PyCue_Summoner_Loop_10504101_OnExecuteAudio) == 0x000008, "Wrong alignment on PyCue_Summoner_Loop_10504101_OnExecuteAudio");
static_assert(sizeof(PyCue_Summoner_Loop_10504101_OnExecuteAudio) == 0x0001C0, "Wrong size on PyCue_Summoner_Loop_10504101_OnExecuteAudio");
static_assert(offsetof(PyCue_Summoner_Loop_10504101_OnExecuteAudio, MyTarget) == 0x000000, "Member 'PyCue_Summoner_Loop_10504101_OnExecuteAudio::MyTarget' has a wrong offset!");
static_assert(offsetof(PyCue_Summoner_Loop_10504101_OnExecuteAudio, Parameters) == 0x000008, "Member 'PyCue_Summoner_Loop_10504101_OnExecuteAudio::Parameters' has a wrong offset!");

// PythonFunction PyAbility_105041.PyCue_Summoner_Loop_10504101.WhileActiveFX
// 0x01C0 (0x01C0 - 0x0000)
struct PyCue_Summoner_Loop_10504101_WhileActiveFX final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PyCue_Summoner_Loop_10504101_WhileActiveFX) == 0x000008, "Wrong alignment on PyCue_Summoner_Loop_10504101_WhileActiveFX");
static_assert(sizeof(PyCue_Summoner_Loop_10504101_WhileActiveFX) == 0x0001C0, "Wrong size on PyCue_Summoner_Loop_10504101_WhileActiveFX");
static_assert(offsetof(PyCue_Summoner_Loop_10504101_WhileActiveFX, MyTarget) == 0x000000, "Member 'PyCue_Summoner_Loop_10504101_WhileActiveFX::MyTarget' has a wrong offset!");
static_assert(offsetof(PyCue_Summoner_Loop_10504101_WhileActiveFX, Parameters) == 0x000008, "Member 'PyCue_Summoner_Loop_10504101_WhileActiveFX::Parameters' has a wrong offset!");

// PythonFunction PyAbility_105041.PyCue_Summoner_Loop_10504101.OnExecuteFX
// 0x01C0 (0x01C0 - 0x0000)
struct PyCue_Summoner_Loop_10504101_OnExecuteFX final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PyCue_Summoner_Loop_10504101_OnExecuteFX) == 0x000008, "Wrong alignment on PyCue_Summoner_Loop_10504101_OnExecuteFX");
static_assert(sizeof(PyCue_Summoner_Loop_10504101_OnExecuteFX) == 0x0001C0, "Wrong size on PyCue_Summoner_Loop_10504101_OnExecuteFX");
static_assert(offsetof(PyCue_Summoner_Loop_10504101_OnExecuteFX, MyTarget) == 0x000000, "Member 'PyCue_Summoner_Loop_10504101_OnExecuteFX::MyTarget' has a wrong offset!");
static_assert(offsetof(PyCue_Summoner_Loop_10504101_OnExecuteFX, Parameters) == 0x000008, "Member 'PyCue_Summoner_Loop_10504101_OnExecuteFX::Parameters' has a wrong offset!");

// PythonFunction PyAbility_105041.PyCue_Summoner_Loop_10504101.OnBarrierTargetChange
// 0x0008 (0x0008 - 0x0000)
struct PyCue_Summoner_Loop_10504101_OnBarrierTargetChange final
{
public:
	class AActor*                                 NewTarget;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyCue_Summoner_Loop_10504101_OnBarrierTargetChange) == 0x000008, "Wrong alignment on PyCue_Summoner_Loop_10504101_OnBarrierTargetChange");
static_assert(sizeof(PyCue_Summoner_Loop_10504101_OnBarrierTargetChange) == 0x000008, "Wrong size on PyCue_Summoner_Loop_10504101_OnBarrierTargetChange");
static_assert(offsetof(PyCue_Summoner_Loop_10504101_OnBarrierTargetChange, NewTarget) == 0x000000, "Member 'PyCue_Summoner_Loop_10504101_OnBarrierTargetChange::NewTarget' has a wrong offset!");

// PythonFunction PyAbility_105041.PyCue_Summoner_Loop_10504101.OnBarrierActiveChange
// 0x0001 (0x0001 - 0x0000)
struct PyCue_Summoner_Loop_10504101_OnBarrierActiveChange final
{
public:
	bool                                          bActive;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyCue_Summoner_Loop_10504101_OnBarrierActiveChange) == 0x000001, "Wrong alignment on PyCue_Summoner_Loop_10504101_OnBarrierActiveChange");
static_assert(sizeof(PyCue_Summoner_Loop_10504101_OnBarrierActiveChange) == 0x000001, "Wrong size on PyCue_Summoner_Loop_10504101_OnBarrierActiveChange");
static_assert(offsetof(PyCue_Summoner_Loop_10504101_OnBarrierActiveChange, bActive) == 0x000000, "Member 'PyCue_Summoner_Loop_10504101_OnBarrierActiveChange::bActive' has a wrong offset!");

// PythonFunction PyAbility_105041.PyCue_Summoner_Loop_10504101.OnBarrierHealthChange
// 0x0020 (0x0020 - 0x0000)
struct PyCue_Summoner_Loop_10504101_OnBarrierHealthChange final
{
public:
	class AActor*                                 InSourceAvatar;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FAttributeModifierHandle               ModifierParameterHandle;                           // 0x0008(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
};
static_assert(alignof(PyCue_Summoner_Loop_10504101_OnBarrierHealthChange) == 0x000008, "Wrong alignment on PyCue_Summoner_Loop_10504101_OnBarrierHealthChange");
static_assert(sizeof(PyCue_Summoner_Loop_10504101_OnBarrierHealthChange) == 0x000020, "Wrong size on PyCue_Summoner_Loop_10504101_OnBarrierHealthChange");
static_assert(offsetof(PyCue_Summoner_Loop_10504101_OnBarrierHealthChange, InSourceAvatar) == 0x000000, "Member 'PyCue_Summoner_Loop_10504101_OnBarrierHealthChange::InSourceAvatar' has a wrong offset!");
static_assert(offsetof(PyCue_Summoner_Loop_10504101_OnBarrierHealthChange, ModifierParameterHandle) == 0x000008, "Member 'PyCue_Summoner_Loop_10504101_OnBarrierHealthChange::ModifierParameterHandle' has a wrong offset!");

// PythonFunction PyAbility_105041.PyCue_Summoner_Loop_10504101.OnRemoveFX
// 0x01C0 (0x01C0 - 0x0000)
struct PyCue_Summoner_Loop_10504101_OnRemoveFX final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PyCue_Summoner_Loop_10504101_OnRemoveFX) == 0x000008, "Wrong alignment on PyCue_Summoner_Loop_10504101_OnRemoveFX");
static_assert(sizeof(PyCue_Summoner_Loop_10504101_OnRemoveFX) == 0x0001C0, "Wrong size on PyCue_Summoner_Loop_10504101_OnRemoveFX");
static_assert(offsetof(PyCue_Summoner_Loop_10504101_OnRemoveFX, MyTarget) == 0x000000, "Member 'PyCue_Summoner_Loop_10504101_OnRemoveFX::MyTarget' has a wrong offset!");
static_assert(offsetof(PyCue_Summoner_Loop_10504101_OnRemoveFX, Parameters) == 0x000008, "Member 'PyCue_Summoner_Loop_10504101_OnRemoveFX::Parameters' has a wrong offset!");

}

