#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbilityActionDisplayOrder

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbilityActionDisplayOrder.PyAbilityActionDisplayOrder
// 0x0020 (0x0058 - 0x0038)
class UPyAbilityActionDisplayOrder final : public UAbilityActionDisplayOrder
{
public:
	TArray<EAbilityInputBinds>                    ActionOrder_MouseAndKeyboard;                      // 0x0038(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TArray<EAbilityInputBinds>                    ActionOrder_Gamepad;                               // 0x0048(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void SortAbilityActionOrder();

	int32 GetAbilityActionDisplayOrder(EAbilityInputBinds AbilityInputBind) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbilityActionDisplayOrder">();
	}
	static class UPyAbilityActionDisplayOrder* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbilityActionDisplayOrder>();
	}
};
static_assert(alignof(UPyAbilityActionDisplayOrder) == 0x000008, "Wrong alignment on UPyAbilityActionDisplayOrder");
static_assert(sizeof(UPyAbilityActionDisplayOrder) == 0x000058, "Wrong size on UPyAbilityActionDisplayOrder");
static_assert(offsetof(UPyAbilityActionDisplayOrder, ActionOrder_MouseAndKeyboard) == 0x000038, "Member 'UPyAbilityActionDisplayOrder::ActionOrder_MouseAndKeyboard' has a wrong offset!");
static_assert(offsetof(UPyAbilityActionDisplayOrder, ActionOrder_Gamepad) == 0x000048, "Member 'UPyAbilityActionDisplayOrder::ActionOrder_Gamepad' has a wrong offset!");

}

