#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_103431

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_103431.PyUIController_103431
// 0x0000 (0x0C60 - 0x0C60)
class UPyUIController_103431 final : public UUIC_Ability
{
public:
	void Destruct();
	void SetAbility(int32 InAbilityId, class UGameplayAbility* InAbility);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyUIController_103431">();
	}
	static class UPyUIController_103431* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyUIController_103431>();
	}
};
static_assert(alignof(UPyUIController_103431) == 0x000008, "Wrong alignment on UPyUIController_103431");
static_assert(sizeof(UPyUIController_103431) == 0x000C60, "Wrong size on UPyUIController_103431");

}

