#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLevelBuffHookerComponent

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyLevelBuffHookerComponent.PyLevelBuffHookerComponent.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct PyLevelBuffHookerComponent_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyLevelBuffHookerComponent_ReceiveEndPlay) == 0x000001, "Wrong alignment on PyLevelBuffHookerComponent_ReceiveEndPlay");
static_assert(sizeof(PyLevelBuffHookerComponent_ReceiveEndPlay) == 0x000001, "Wrong size on PyLevelBuffHookerComponent_ReceiveEndPlay");
static_assert(offsetof(PyLevelBuffHookerComponent_ReceiveEndPlay, EndPlayReason) == 0x000000, "Member 'PyLevelBuffHookerComponent_ReceiveEndPlay::EndPlayReason' has a wrong offset!");

}

