#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLevelFog

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Marvel_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// PythonClass PyLevelFog.PyLevelFog
// 0x0088 (0x0518 - 0x0490)
class APyLevelFog final : public AMarvelLevelActorBase
{
public:
	float                                         FoggyProgress;                                     // 0x0490(0x0004)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         State;                                             // 0x0494(0x0004)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          DefaultActive;                                     // 0x0498(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_499[0x3];                                      // 0x0499(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         BlindBuffID;                                       // 0x049C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         HiddenBuffID;                                      // 0x04A0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FadeInTime;                                        // 0x04A4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FadeoutTime;                                       // 0x04A8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DelayTime;                                         // 0x04AC(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DurationTime;                                      // 0x04B0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4B4[0x4];                                      // 0x04B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AEnvironmentStaticActor*>        AtlasMeshList;                                     // 0x04B8(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FGameplayTag                           CueTag;                                            // 0x04C8(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RadiusMax;                                         // 0x04D4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RadiusMin;                                         // 0x04D8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CameraLengthMax;                                   // 0x04DC(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CameraLengthMin;                                   // 0x04E0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DecalRaius;                                        // 0x04E4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             FogStateChangedDispatcher;                         // 0x04E8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnStopTakeEffect;                                  // 0x04F8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             ClientToggleBlindBuff;                             // 0x0508(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void FogStateChangedDispatcher__DelegateSignature(int32 NewState);
	void OnStopTakeEffect__DelegateSignature();
	void ClientToggleBlindBuff__DelegateSignature(bool Enable, class AActor* OtherActor);
	void ReceiveInit();
	void ReceiveBeginPlay();
	void OnLevelStart();
	void ReceiveTick(float DeltaSeconds);
	void OnPlayerSpawn(class AMarvelPlayerState* PlayerState);
	void OnRep_State();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyLevelFog">();
	}
	static class APyLevelFog* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyLevelFog>();
	}
};
static_assert(alignof(APyLevelFog) == 0x000008, "Wrong alignment on APyLevelFog");
static_assert(sizeof(APyLevelFog) == 0x000518, "Wrong size on APyLevelFog");
static_assert(offsetof(APyLevelFog, FoggyProgress) == 0x000490, "Member 'APyLevelFog::FoggyProgress' has a wrong offset!");
static_assert(offsetof(APyLevelFog, State) == 0x000494, "Member 'APyLevelFog::State' has a wrong offset!");
static_assert(offsetof(APyLevelFog, DefaultActive) == 0x000498, "Member 'APyLevelFog::DefaultActive' has a wrong offset!");
static_assert(offsetof(APyLevelFog, BlindBuffID) == 0x00049C, "Member 'APyLevelFog::BlindBuffID' has a wrong offset!");
static_assert(offsetof(APyLevelFog, HiddenBuffID) == 0x0004A0, "Member 'APyLevelFog::HiddenBuffID' has a wrong offset!");
static_assert(offsetof(APyLevelFog, FadeInTime) == 0x0004A4, "Member 'APyLevelFog::FadeInTime' has a wrong offset!");
static_assert(offsetof(APyLevelFog, FadeoutTime) == 0x0004A8, "Member 'APyLevelFog::FadeoutTime' has a wrong offset!");
static_assert(offsetof(APyLevelFog, DelayTime) == 0x0004AC, "Member 'APyLevelFog::DelayTime' has a wrong offset!");
static_assert(offsetof(APyLevelFog, DurationTime) == 0x0004B0, "Member 'APyLevelFog::DurationTime' has a wrong offset!");
static_assert(offsetof(APyLevelFog, AtlasMeshList) == 0x0004B8, "Member 'APyLevelFog::AtlasMeshList' has a wrong offset!");
static_assert(offsetof(APyLevelFog, CueTag) == 0x0004C8, "Member 'APyLevelFog::CueTag' has a wrong offset!");
static_assert(offsetof(APyLevelFog, RadiusMax) == 0x0004D4, "Member 'APyLevelFog::RadiusMax' has a wrong offset!");
static_assert(offsetof(APyLevelFog, RadiusMin) == 0x0004D8, "Member 'APyLevelFog::RadiusMin' has a wrong offset!");
static_assert(offsetof(APyLevelFog, CameraLengthMax) == 0x0004DC, "Member 'APyLevelFog::CameraLengthMax' has a wrong offset!");
static_assert(offsetof(APyLevelFog, CameraLengthMin) == 0x0004E0, "Member 'APyLevelFog::CameraLengthMin' has a wrong offset!");
static_assert(offsetof(APyLevelFog, DecalRaius) == 0x0004E4, "Member 'APyLevelFog::DecalRaius' has a wrong offset!");
static_assert(offsetof(APyLevelFog, FogStateChangedDispatcher) == 0x0004E8, "Member 'APyLevelFog::FogStateChangedDispatcher' has a wrong offset!");
static_assert(offsetof(APyLevelFog, OnStopTakeEffect) == 0x0004F8, "Member 'APyLevelFog::OnStopTakeEffect' has a wrong offset!");
static_assert(offsetof(APyLevelFog, ClientToggleBlindBuff) == 0x000508, "Member 'APyLevelFog::ClientToggleBlindBuff' has a wrong offset!");

// PythonClass PyLevelFog.PyCue_Summoner_Loop_20020902
// 0x0000 (0x11A8 - 0x11A8)
class APyCue_Summoner_Loop_20020902 final : public ACueNotify_Stealth
{
public:
	bool WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Summoner_Loop_20020902">();
	}
	static class APyCue_Summoner_Loop_20020902* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Summoner_Loop_20020902>();
	}
};
static_assert(alignof(APyCue_Summoner_Loop_20020902) == 0x000008, "Wrong alignment on APyCue_Summoner_Loop_20020902");
static_assert(sizeof(APyCue_Summoner_Loop_20020902) == 0x0011A8, "Wrong size on APyCue_Summoner_Loop_20020902");

}

