#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyMarvelTeamState

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyMarvelTeamState.PyMarvelTeamState
// 0x0008 (0x04A0 - 0x0498)
class APyMarvelTeamState final : public AMarvelTeamState
{
public:
	class UPyTeamStateVoteComponent*              VoteComp;                                          // 0x0498(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyMarvelTeamState">();
	}
	static class APyMarvelTeamState* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyMarvelTeamState>();
	}
};
static_assert(alignof(APyMarvelTeamState) == 0x000008, "Wrong alignment on APyMarvelTeamState");
static_assert(sizeof(APyMarvelTeamState) == 0x0004A0, "Wrong size on APyMarvelTeamState");
static_assert(offsetof(APyMarvelTeamState, VoteComp) == 0x000498, "Member 'APyMarvelTeamState::VoteComp' has a wrong offset!");

}

