#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyMisterFantasticCharacter

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyMisterFantasticCharacter.PyMisterFantasticCharacter.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct PyMisterFantasticCharacter_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyMisterFantasticCharacter_ReceiveEndPlay) == 0x000001, "Wrong alignment on PyMisterFantasticCharacter_ReceiveEndPlay");
static_assert(sizeof(PyMisterFantasticCharacter_ReceiveEndPlay) == 0x000001, "Wrong size on PyMisterFantasticCharacter_ReceiveEndPlay");
static_assert(offsetof(PyMisterFantasticCharacter_ReceiveEndPlay, EndPlayReason) == 0x000000, "Member 'PyMisterFantasticCharacter_ReceiveEndPlay::EndPlayReason' has a wrong offset!");

// PythonFunction PyMisterFantasticCharacter.PyMisterFantasticCharacter.OnHeroReviving
// 0x0001 (0x0001 - 0x0000)
struct PyMisterFantasticCharacter_OnHeroReviving final
{
public:
	EPlayerLivingState                            State;                                             // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyMisterFantasticCharacter_OnHeroReviving) == 0x000001, "Wrong alignment on PyMisterFantasticCharacter_OnHeroReviving");
static_assert(sizeof(PyMisterFantasticCharacter_OnHeroReviving) == 0x000001, "Wrong size on PyMisterFantasticCharacter_OnHeroReviving");
static_assert(offsetof(PyMisterFantasticCharacter_OnHeroReviving, State) == 0x000000, "Member 'PyMisterFantasticCharacter_OnHeroReviving::State' has a wrong offset!");

// PythonFunction PyMisterFantasticCharacter.PyMisterFantasticCharacter.OnPreDeath
// 0x0028 (0x0028 - 0x0000)
struct PyMisterFantasticCharacter_OnPreDeath final
{
public:
	class AController*                            InSource;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 InSourceAvatar;                                    // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FAttributeModifierHandle               ModifierParameter;                                 // 0x0010(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
};
static_assert(alignof(PyMisterFantasticCharacter_OnPreDeath) == 0x000008, "Wrong alignment on PyMisterFantasticCharacter_OnPreDeath");
static_assert(sizeof(PyMisterFantasticCharacter_OnPreDeath) == 0x000028, "Wrong size on PyMisterFantasticCharacter_OnPreDeath");
static_assert(offsetof(PyMisterFantasticCharacter_OnPreDeath, InSource) == 0x000000, "Member 'PyMisterFantasticCharacter_OnPreDeath::InSource' has a wrong offset!");
static_assert(offsetof(PyMisterFantasticCharacter_OnPreDeath, InSourceAvatar) == 0x000008, "Member 'PyMisterFantasticCharacter_OnPreDeath::InSourceAvatar' has a wrong offset!");
static_assert(offsetof(PyMisterFantasticCharacter_OnPreDeath, ModifierParameter) == 0x000010, "Member 'PyMisterFantasticCharacter_OnPreDeath::ModifierParameter' has a wrong offset!");

// PythonFunction PyMisterFantasticCharacter.PyMisterFantasticCharacter.OnReborn
// 0x0730 (0x0730 - 0x0000)
struct PyMisterFantasticCharacter_OnReborn final
{
public:
	struct FCharacterRebornParam                  RebornParameter;                                   // 0x0000(0x0730)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PyMisterFantasticCharacter_OnReborn) == 0x000010, "Wrong alignment on PyMisterFantasticCharacter_OnReborn");
static_assert(sizeof(PyMisterFantasticCharacter_OnReborn) == 0x000730, "Wrong size on PyMisterFantasticCharacter_OnReborn");
static_assert(offsetof(PyMisterFantasticCharacter_OnReborn, RebornParameter) == 0x000000, "Member 'PyMisterFantasticCharacter_OnReborn::RebornParameter' has a wrong offset!");

}

