#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PySubVoMgr_Chat

#include "Basic.hpp"

#include "PySubVoMgrBase_classes.hpp"


namespace SDK
{

// PythonClass PySubVoMgr_Chat.PySubVoMgr_Chat
// 0x0000 (0x00F0 - 0x00F0)
class UPySubVoMgr_Chat final : public UPySubVoMgrBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PySubVoMgr_Chat">();
	}
	static class UPySubVoMgr_Chat* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPySubVoMgr_Chat>();
	}
};
static_assert(alignof(UPySubVoMgr_Chat) == 0x000008, "Wrong alignment on UPySubVoMgr_Chat");
static_assert(sizeof(UPySubVoMgr_Chat) == 0x0000F0, "Wrong size on UPySubVoMgr_Chat");

}

