#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_BuffPanel

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_BuffPanel.PyWidget_BuffDebugPanel
// 0x0080 (0x0670 - 0x05F0)
class UPyWidget_BuffDebugPanel : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E9[0x7];                                      // 0x05E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UUserWidget>                BuffBtn;                                           // 0x05F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CurrentRow;                                        // 0x05F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5FC[0x4];                                      // 0x05FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<int32, class UUserWidget*>               BuffInfo;                                          // 0x0600(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TArray<class UUserWidget*>                    BtnList;                                           // 0x0650(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class UUserWidget*                            CurrentBtn;                                        // 0x0660(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UUserWidget*                            CheckEffectSet;                                    // 0x0668(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void BindCmdEvent();
	void OnRightClicked();
	void Construct();
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_BuffDebugPanel">();
	}
	static class UPyWidget_BuffDebugPanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_BuffDebugPanel>();
	}
};
static_assert(alignof(UPyWidget_BuffDebugPanel) == 0x000008, "Wrong alignment on UPyWidget_BuffDebugPanel");
static_assert(sizeof(UPyWidget_BuffDebugPanel) == 0x000670, "Wrong size on UPyWidget_BuffDebugPanel");
static_assert(offsetof(UPyWidget_BuffDebugPanel, BuffBtn) == 0x0005F0, "Member 'UPyWidget_BuffDebugPanel::BuffBtn' has a wrong offset!");
static_assert(offsetof(UPyWidget_BuffDebugPanel, CurrentRow) == 0x0005F8, "Member 'UPyWidget_BuffDebugPanel::CurrentRow' has a wrong offset!");
static_assert(offsetof(UPyWidget_BuffDebugPanel, BuffInfo) == 0x000600, "Member 'UPyWidget_BuffDebugPanel::BuffInfo' has a wrong offset!");
static_assert(offsetof(UPyWidget_BuffDebugPanel, BtnList) == 0x000650, "Member 'UPyWidget_BuffDebugPanel::BtnList' has a wrong offset!");
static_assert(offsetof(UPyWidget_BuffDebugPanel, CurrentBtn) == 0x000660, "Member 'UPyWidget_BuffDebugPanel::CurrentBtn' has a wrong offset!");
static_assert(offsetof(UPyWidget_BuffDebugPanel, CheckEffectSet) == 0x000668, "Member 'UPyWidget_BuffDebugPanel::CheckEffectSet' has a wrong offset!");

}

