#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_SettingPageLimitTimeTraining

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "PyWidget_ModuleMainPanel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_SettingPageLimitTimeTraining.PyWidget_SettingPageLimitTimeTraining
// 0x0018 (0x0630 - 0x0618)
class UPyWidget_SettingPageLimitTimeTraining : public UPyWidget_ModuleMainPanel
{
public:
	uint8                                         Pad_611[0x7];                                      // 0x0611(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UDataTable*                             PageTable;                                         // 0x0618(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FGuideTipsStyle>                ApplyGuideTipsStyle;                               // 0x0620(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	void MarvelSetVisible(bool Visible);
	void Destruct();
	void Construct();
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_SettingPageLimitTimeTraining">();
	}
	static class UPyWidget_SettingPageLimitTimeTraining* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_SettingPageLimitTimeTraining>();
	}
};
static_assert(alignof(UPyWidget_SettingPageLimitTimeTraining) == 0x000008, "Wrong alignment on UPyWidget_SettingPageLimitTimeTraining");
static_assert(sizeof(UPyWidget_SettingPageLimitTimeTraining) == 0x000630, "Wrong size on UPyWidget_SettingPageLimitTimeTraining");
static_assert(offsetof(UPyWidget_SettingPageLimitTimeTraining, PageTable) == 0x000618, "Member 'UPyWidget_SettingPageLimitTimeTraining::PageTable' has a wrong offset!");
static_assert(offsetof(UPyWidget_SettingPageLimitTimeTraining, ApplyGuideTipsStyle) == 0x000620, "Member 'UPyWidget_SettingPageLimitTimeTraining::ApplyGuideTipsStyle' has a wrong offset!");

}

