#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget3D_BuffMonitor

#include "Basic.hpp"

#include "PyWidget3D_BuffMonitor_classes.hpp"
#include "PyWidget3D_BuffMonitor_parameters.hpp"


namespace SDK
{

// PythonFunction PyWidget3D_BuffMonitor.PyWidget3D_BuffMonitor.K2_MainStyle
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget3D_BuffMonitor::K2_MainStyle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget3D_BuffMonitor", "K2_MainStyle");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget3D_BuffMonitor.PyWidget3D_BuffMonitor.OwnerCueActiveChanged
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget3D_BuffMonitor::OwnerCueActiveChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget3D_BuffMonitor", "OwnerCueActiveChanged");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget3D_BuffMonitor.PyWidget3D_BuffMonitor.ShouldBeVisible
// (Native, Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UPyWidget3D_BuffMonitor::ShouldBeVisible()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget3D_BuffMonitor", "ShouldBeVisible");

	Params::PyWidget3D_BuffMonitor_ShouldBeVisible Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// PythonFunction PyWidget3D_BuffMonitor.PyWidget3D_BuffMonitor.OnInitialized
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget3D_BuffMonitor::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget3D_BuffMonitor", "OnInitialized");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

