#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_BanPickTips

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_BanPickTips.PyWidget_BanPickTipsConfirmedUnit.MarvelSetVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_BanPickTipsConfirmedUnit_MarvelSetVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_BanPickTipsConfirmedUnit_MarvelSetVisible) == 0x000001, "Wrong alignment on PyWidget_BanPickTipsConfirmedUnit_MarvelSetVisible");
static_assert(sizeof(PyWidget_BanPickTipsConfirmedUnit_MarvelSetVisible) == 0x000001, "Wrong size on PyWidget_BanPickTipsConfirmedUnit_MarvelSetVisible");
static_assert(offsetof(PyWidget_BanPickTipsConfirmedUnit_MarvelSetVisible, Visible) == 0x000000, "Member 'PyWidget_BanPickTipsConfirmedUnit_MarvelSetVisible::Visible' has a wrong offset!");

}

