#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Mall_Recommend

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "PyWidget_Mall_BundlePageList_Panel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Mall_Recommend.PyWidget_Mall_Recommend_Panel
// 0x00A8 (0x06C0 - 0x0618)
class UPyWidget_Mall_Recommend_Panel final : public UPyWidget_Mall_BundlePageList_Panel
{
public:
	TSubclassOf<class UUserWidget>                Row_Item_With_2_Cards;                             // 0x0618(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UUserWidget>                Row_Item_With_4_Cards;                             // 0x0620(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FMargin                                ThePadding_of_FirstCard;                           // 0x0628(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FMargin                                ThePadding_of_2_Cards;                             // 0x0638(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FMargin                                ThePadding_of_4_Cards;                             // 0x0648(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	int32                                         Max_row_count_in_page;                             // 0x0658(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FMargin                                ThePadding_of_Overlay_Content;                     // 0x065C(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FMargin                                ThePadding_of_Overlay_Content_FullPage;            // 0x066C(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_67C[0x4];                                      // 0x067C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             SelectHeroIcon_Normal;                             // 0x0680(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             SelectHeroIcon_Selected;                           // 0x0688(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class UUserWidget*>                    FullScreenWidgets;                                 // 0x0690(0x0010)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FVector2D                              ScaleOfFullScreenArrow;                            // 0x06A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnArrowBtnHoveredChanged;                          // 0x06B0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void OnArrowBtnHoveredChanged__DelegateSignature(bool IsHovered_0);
	void OnInitialized();
	void Construct();
	void Destruct();
	void OnAnimationFinished(const class UWidgetAnimation* Animation);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Mall_Recommend_Panel">();
	}
	static class UPyWidget_Mall_Recommend_Panel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Mall_Recommend_Panel>();
	}
};
static_assert(alignof(UPyWidget_Mall_Recommend_Panel) == 0x000008, "Wrong alignment on UPyWidget_Mall_Recommend_Panel");
static_assert(sizeof(UPyWidget_Mall_Recommend_Panel) == 0x0006C0, "Wrong size on UPyWidget_Mall_Recommend_Panel");
static_assert(offsetof(UPyWidget_Mall_Recommend_Panel, Row_Item_With_2_Cards) == 0x000618, "Member 'UPyWidget_Mall_Recommend_Panel::Row_Item_With_2_Cards' has a wrong offset!");
static_assert(offsetof(UPyWidget_Mall_Recommend_Panel, Row_Item_With_4_Cards) == 0x000620, "Member 'UPyWidget_Mall_Recommend_Panel::Row_Item_With_4_Cards' has a wrong offset!");
static_assert(offsetof(UPyWidget_Mall_Recommend_Panel, ThePadding_of_FirstCard) == 0x000628, "Member 'UPyWidget_Mall_Recommend_Panel::ThePadding_of_FirstCard' has a wrong offset!");
static_assert(offsetof(UPyWidget_Mall_Recommend_Panel, ThePadding_of_2_Cards) == 0x000638, "Member 'UPyWidget_Mall_Recommend_Panel::ThePadding_of_2_Cards' has a wrong offset!");
static_assert(offsetof(UPyWidget_Mall_Recommend_Panel, ThePadding_of_4_Cards) == 0x000648, "Member 'UPyWidget_Mall_Recommend_Panel::ThePadding_of_4_Cards' has a wrong offset!");
static_assert(offsetof(UPyWidget_Mall_Recommend_Panel, Max_row_count_in_page) == 0x000658, "Member 'UPyWidget_Mall_Recommend_Panel::Max_row_count_in_page' has a wrong offset!");
static_assert(offsetof(UPyWidget_Mall_Recommend_Panel, ThePadding_of_Overlay_Content) == 0x00065C, "Member 'UPyWidget_Mall_Recommend_Panel::ThePadding_of_Overlay_Content' has a wrong offset!");
static_assert(offsetof(UPyWidget_Mall_Recommend_Panel, ThePadding_of_Overlay_Content_FullPage) == 0x00066C, "Member 'UPyWidget_Mall_Recommend_Panel::ThePadding_of_Overlay_Content_FullPage' has a wrong offset!");
static_assert(offsetof(UPyWidget_Mall_Recommend_Panel, SelectHeroIcon_Normal) == 0x000680, "Member 'UPyWidget_Mall_Recommend_Panel::SelectHeroIcon_Normal' has a wrong offset!");
static_assert(offsetof(UPyWidget_Mall_Recommend_Panel, SelectHeroIcon_Selected) == 0x000688, "Member 'UPyWidget_Mall_Recommend_Panel::SelectHeroIcon_Selected' has a wrong offset!");
static_assert(offsetof(UPyWidget_Mall_Recommend_Panel, FullScreenWidgets) == 0x000690, "Member 'UPyWidget_Mall_Recommend_Panel::FullScreenWidgets' has a wrong offset!");
static_assert(offsetof(UPyWidget_Mall_Recommend_Panel, ScaleOfFullScreenArrow) == 0x0006A0, "Member 'UPyWidget_Mall_Recommend_Panel::ScaleOfFullScreenArrow' has a wrong offset!");
static_assert(offsetof(UPyWidget_Mall_Recommend_Panel, OnArrowBtnHoveredChanged) == 0x0006B0, "Member 'UPyWidget_Mall_Recommend_Panel::OnArrowBtnHoveredChanged' has a wrong offset!");

}

