#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_SecondaryPopupPanel

#include "Basic.hpp"

#include "Marvel_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_PreConstruct) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_PreConstruct");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_PreConstruct) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_PreConstruct");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_PreConstruct, IsDesignTime) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_PreConstruct::IsDesignTime' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.ShouldEnableInput
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_ShouldEnableInput final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_ShouldEnableInput) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_ShouldEnableInput");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_ShouldEnableInput) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_ShouldEnableInput");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_ShouldEnableInput, ReturnValue) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_ShouldEnableInput::ReturnValue' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.CloseRecommendRecharge
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_CloseRecommendRecharge final
{
public:
	bool                                          IsVisible_0;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_CloseRecommendRecharge) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_CloseRecommendRecharge");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_CloseRecommendRecharge) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_CloseRecommendRecharge");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_CloseRecommendRecharge, IsVisible_0) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_CloseRecommendRecharge::IsVisible_0' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.OnActiveStateChange
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_OnActiveStateChange final
{
public:
	bool                                          bInActive;                                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_OnActiveStateChange) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_OnActiveStateChange");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_OnActiveStateChange) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_OnActiveStateChange");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_OnActiveStateChange, bInActive) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_OnActiveStateChange::bInActive' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetCommonBGType
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetCommonBGType final
{
public:
	ECommonBGType                                 CommonBGType_0;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetCommonBGType) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetCommonBGType");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetCommonBGType) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_SetCommonBGType");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetCommonBGType, CommonBGType_0) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetCommonBGType::CommonBGType_0' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetTitleText
// 0x0018 (0x0018 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetTitleText final
{
public:
	class FText                                   TitleText_0;                                       // 0x0000(0x0018)(Parm)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetTitleText) == 0x000008, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetTitleText");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetTitleText) == 0x000018, "Wrong size on PyWidget_SecondaryPopupPanel_SetTitleText");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetTitleText, TitleText_0) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetTitleText::TitleText_0' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetTitleTimeCountDown
// 0x0008 (0x0008 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetTitleTimeCountDown final
{
public:
	int32                                         TimeCountDown;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         WaitTime;                                          // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetTitleTimeCountDown) == 0x000004, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetTitleTimeCountDown");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetTitleTimeCountDown) == 0x000008, "Wrong size on PyWidget_SecondaryPopupPanel_SetTitleTimeCountDown");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetTitleTimeCountDown, TimeCountDown) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetTitleTimeCountDown::TimeCountDown' has a wrong offset!");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetTitleTimeCountDown, WaitTime) == 0x000004, "Member 'PyWidget_SecondaryPopupPanel_SetTitleTimeCountDown::WaitTime' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetBtnsText
// 0x0048 (0x0048 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetBtnsText final
{
public:
	class FText                                   LeftBtnText_0;                                     // 0x0000(0x0018)(Parm)
	class FText                                   RightBtnText_0;                                    // 0x0018(0x0018)(Parm)
	class FText                                   Close_btn_text;                                    // 0x0030(0x0018)(Parm)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetBtnsText) == 0x000008, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetBtnsText");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetBtnsText) == 0x000048, "Wrong size on PyWidget_SecondaryPopupPanel_SetBtnsText");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetBtnsText, LeftBtnText_0) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetBtnsText::LeftBtnText_0' has a wrong offset!");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetBtnsText, RightBtnText_0) == 0x000018, "Member 'PyWidget_SecondaryPopupPanel_SetBtnsText::RightBtnText_0' has a wrong offset!");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetBtnsText, Close_btn_text) == 0x000030, "Member 'PyWidget_SecondaryPopupPanel_SetBtnsText::Close_btn_text' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetLeftBtnText
// 0x0018 (0x0018 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetLeftBtnText final
{
public:
	class FText                                   LeftBtnText_0;                                     // 0x0000(0x0018)(Parm)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetLeftBtnText) == 0x000008, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetLeftBtnText");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetLeftBtnText) == 0x000018, "Wrong size on PyWidget_SecondaryPopupPanel_SetLeftBtnText");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetLeftBtnText, LeftBtnText_0) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetLeftBtnText::LeftBtnText_0' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetRightBtnText
// 0x0018 (0x0018 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetRightBtnText final
{
public:
	class FText                                   RightBtnText_0;                                    // 0x0000(0x0018)(Parm)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetRightBtnText) == 0x000008, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetRightBtnText");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetRightBtnText) == 0x000018, "Wrong size on PyWidget_SecondaryPopupPanel_SetRightBtnText");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetRightBtnText, RightBtnText_0) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetRightBtnText::RightBtnText_0' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetCloseBtnText
// 0x0018 (0x0018 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetCloseBtnText final
{
public:
	class FText                                   BtnText;                                           // 0x0000(0x0018)(Parm)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetCloseBtnText) == 0x000008, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetCloseBtnText");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetCloseBtnText) == 0x000018, "Wrong size on PyWidget_SecondaryPopupPanel_SetCloseBtnText");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetCloseBtnText, BtnText) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetCloseBtnText::BtnText' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetBtnAboveTipsText
// 0x0030 (0x0030 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetBtnAboveTipsText final
{
public:
	class FText                                   LeftTips;                                          // 0x0000(0x0018)(Parm)
	class FText                                   RightTips;                                         // 0x0018(0x0018)(Parm)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetBtnAboveTipsText) == 0x000008, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetBtnAboveTipsText");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetBtnAboveTipsText) == 0x000030, "Wrong size on PyWidget_SecondaryPopupPanel_SetBtnAboveTipsText");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetBtnAboveTipsText, LeftTips) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetBtnAboveTipsText::LeftTips' has a wrong offset!");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetBtnAboveTipsText, RightTips) == 0x000018, "Member 'PyWidget_SecondaryPopupPanel_SetBtnAboveTipsText::RightTips' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetLeftBtnEnabled
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetLeftBtnEnabled final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetLeftBtnEnabled) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetLeftBtnEnabled");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetLeftBtnEnabled) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_SetLeftBtnEnabled");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetLeftBtnEnabled, Enabled) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetLeftBtnEnabled::Enabled' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetRightBtnEnabled
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetRightBtnEnabled final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetRightBtnEnabled) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetRightBtnEnabled");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetRightBtnEnabled) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_SetRightBtnEnabled");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetRightBtnEnabled, Enabled) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetRightBtnEnabled::Enabled' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetTitleVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetTitleVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetTitleVisible) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetTitleVisible");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetTitleVisible) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_SetTitleVisible");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetTitleVisible, Visible) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetTitleVisible::Visible' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetBtnsVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetBtnsVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetBtnsVisible) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetBtnsVisible");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetBtnsVisible) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_SetBtnsVisible");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetBtnsVisible, Visible) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetBtnsVisible::Visible' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetLeftBtnVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetLeftBtnVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetLeftBtnVisible) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetLeftBtnVisible");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetLeftBtnVisible) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_SetLeftBtnVisible");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetLeftBtnVisible, Visible) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetLeftBtnVisible::Visible' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetLeftWhiteBtnVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetLeftWhiteBtnVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetLeftWhiteBtnVisible) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetLeftWhiteBtnVisible");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetLeftWhiteBtnVisible) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_SetLeftWhiteBtnVisible");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetLeftWhiteBtnVisible, Visible) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetLeftWhiteBtnVisible::Visible' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetLeftBtnTipsVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetLeftBtnTipsVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetLeftBtnTipsVisible) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetLeftBtnTipsVisible");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetLeftBtnTipsVisible) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_SetLeftBtnTipsVisible");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetLeftBtnTipsVisible, Visible) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetLeftBtnTipsVisible::Visible' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetRightBtnVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetRightBtnVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetRightBtnVisible) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetRightBtnVisible");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetRightBtnVisible) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_SetRightBtnVisible");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetRightBtnVisible, Visible) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetRightBtnVisible::Visible' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetRightBtnTipsVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetRightBtnTipsVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetRightBtnTipsVisible) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetRightBtnTipsVisible");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetRightBtnTipsVisible) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_SetRightBtnTipsVisible");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetRightBtnTipsVisible, Visible) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetRightBtnTipsVisible::Visible' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetRightBtn2Visible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetRightBtn2Visible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetRightBtn2Visible) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetRightBtn2Visible");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetRightBtn2Visible) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_SetRightBtn2Visible");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetRightBtn2Visible, Visible) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetRightBtn2Visible::Visible' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetBtnAboveTipsVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetBtnAboveTipsVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetBtnAboveTipsVisible) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetBtnAboveTipsVisible");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetBtnAboveTipsVisible) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_SetBtnAboveTipsVisible");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetBtnAboveTipsVisible, Visible) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetBtnAboveTipsVisible::Visible' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetRightBtnYellowVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetRightBtnYellowVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetRightBtnYellowVisible) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetRightBtnYellowVisible");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetRightBtnYellowVisible) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_SetRightBtnYellowVisible");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetRightBtnYellowVisible, Visible) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetRightBtnYellowVisible::Visible' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.SetLeftBtnTwoPrice
// 0x0030 (0x0030 - 0x0000)
struct PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice final
{
public:
	class FString                                 Cost_id1;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
	int32                                         Price1;                                            // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Is_enough1;                                        // 0x0014(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Cost_id2;                                          // 0x0018(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
	int32                                         Price2;                                            // 0x0028(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Is_enough2;                                        // 0x002C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice) == 0x000008, "Wrong alignment on PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice) == 0x000030, "Wrong size on PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice, Cost_id1) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice::Cost_id1' has a wrong offset!");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice, Price1) == 0x000010, "Member 'PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice::Price1' has a wrong offset!");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice, Is_enough1) == 0x000014, "Member 'PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice::Is_enough1' has a wrong offset!");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice, Cost_id2) == 0x000018, "Member 'PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice::Cost_id2' has a wrong offset!");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice, Price2) == 0x000028, "Member 'PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice::Price2' has a wrong offset!");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice, Is_enough2) == 0x00002C, "Member 'PyWidget_SecondaryPopupPanel_SetLeftBtnTwoPrice::Is_enough2' has a wrong offset!");

// PythonFunction PyWidget_SecondaryPopupPanel.PyWidget_SecondaryPopupPanel.MarvelSetVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SecondaryPopupPanel_MarvelSetVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_SecondaryPopupPanel_MarvelSetVisible) == 0x000001, "Wrong alignment on PyWidget_SecondaryPopupPanel_MarvelSetVisible");
static_assert(sizeof(PyWidget_SecondaryPopupPanel_MarvelSetVisible) == 0x000001, "Wrong size on PyWidget_SecondaryPopupPanel_MarvelSetVisible");
static_assert(offsetof(PyWidget_SecondaryPopupPanel_MarvelSetVisible, Visible) == 0x000000, "Member 'PyWidget_SecondaryPopupPanel_MarvelSetVisible::Visible' has a wrong offset!");

}

