#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_CareerPersonalRecord

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "Marvel_structs.hpp"
#include "PyMarvelUserWidget_classes.hpp"
#include "SlateCore_structs.hpp"
#include "PyWidget_Button_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_CareerPersonalRecord.PyWidget_CareerPersonalRecord_Item
// 0x0550 (0x0CA0 - 0x0750)
#pragma pack(push, 0x1)
class alignas(0x10) UPyWidget_CareerPersonalRecord_Item : public UPyWidget_Button
{
public:
	struct FSlateBrush                            TextureWin;                                        // 0x0750(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateBrush                            TextureLose;                                       // 0x0820(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateBrush                            TextureDraw;                                       // 0x08F0(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateBrush                            TextureWinHovered;                                 // 0x09C0(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateBrush                            TextureLoseHovered;                                // 0x0A90(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateBrush                            TextureDrawHovered;                                // 0x0B60(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AkEvent_OnButtonReplayClicked;                     // 0x0C30(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AkEvent_OnButtonReplayHovered;                     // 0x0C38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSlateColor                            Color_Score_Non;                                   // 0x0C40(0x0014)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FSlateColor                            Color_Score_Add;                                   // 0x0C54(0x0014)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FSlateColor                            Color_Score_Sub;                                   // 0x0C68(0x0014)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	uint8                                         Pad_C7C[0x4];                                      // 0x0C7C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             TextureCommon_K;                                   // 0x0C80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             TextureCommon_D;                                   // 0x0C88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             TextureCommon_A;                                   // 0x0C90(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void SetInfoDict(class UObject* Info);
	void OnAnimationFinished(const class UWidgetAnimation* Animation);
	void OnAnimationsDisabled();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_CareerPersonalRecord_Item">();
	}
	static class UPyWidget_CareerPersonalRecord_Item* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_CareerPersonalRecord_Item>();
	}
};
#pragma pack(pop)
static_assert(alignof(UPyWidget_CareerPersonalRecord_Item) == 0x000010, "Wrong alignment on UPyWidget_CareerPersonalRecord_Item");
static_assert(sizeof(UPyWidget_CareerPersonalRecord_Item) == 0x000CA0, "Wrong size on UPyWidget_CareerPersonalRecord_Item");
static_assert(offsetof(UPyWidget_CareerPersonalRecord_Item, TextureWin) == 0x000750, "Member 'UPyWidget_CareerPersonalRecord_Item::TextureWin' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord_Item, TextureLose) == 0x000820, "Member 'UPyWidget_CareerPersonalRecord_Item::TextureLose' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord_Item, TextureDraw) == 0x0008F0, "Member 'UPyWidget_CareerPersonalRecord_Item::TextureDraw' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord_Item, TextureWinHovered) == 0x0009C0, "Member 'UPyWidget_CareerPersonalRecord_Item::TextureWinHovered' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord_Item, TextureLoseHovered) == 0x000A90, "Member 'UPyWidget_CareerPersonalRecord_Item::TextureLoseHovered' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord_Item, TextureDrawHovered) == 0x000B60, "Member 'UPyWidget_CareerPersonalRecord_Item::TextureDrawHovered' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord_Item, AkEvent_OnButtonReplayClicked) == 0x000C30, "Member 'UPyWidget_CareerPersonalRecord_Item::AkEvent_OnButtonReplayClicked' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord_Item, AkEvent_OnButtonReplayHovered) == 0x000C38, "Member 'UPyWidget_CareerPersonalRecord_Item::AkEvent_OnButtonReplayHovered' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord_Item, Color_Score_Non) == 0x000C40, "Member 'UPyWidget_CareerPersonalRecord_Item::Color_Score_Non' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord_Item, Color_Score_Add) == 0x000C54, "Member 'UPyWidget_CareerPersonalRecord_Item::Color_Score_Add' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord_Item, Color_Score_Sub) == 0x000C68, "Member 'UPyWidget_CareerPersonalRecord_Item::Color_Score_Sub' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord_Item, TextureCommon_K) == 0x000C80, "Member 'UPyWidget_CareerPersonalRecord_Item::TextureCommon_K' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord_Item, TextureCommon_D) == 0x000C88, "Member 'UPyWidget_CareerPersonalRecord_Item::TextureCommon_D' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord_Item, TextureCommon_A) == 0x000C90, "Member 'UPyWidget_CareerPersonalRecord_Item::TextureCommon_A' has a wrong offset!");

// PythonClass PyWidget_CareerPersonalRecord.PyWidget_CareerPersonalRecord
// 0x0330 (0x0920 - 0x05F0)
class UPyWidget_CareerPersonalRecord final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E9[0x3];                                      // 0x05E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         FadeInAnimInterval;                                // 0x05EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGuideTipsStyle                        ScrollListGuideTipsStyle;                          // 0x05F0(0x0110)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FGuideTipsStyle                        ShowDetailGuideTipsStyle;                          // 0x0700(0x0110)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FGuideTipsStyle                        PlayBackGuideTipsStyle;                            // 0x0810(0x0110)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void MarvelSetVisible(bool Visible);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_CareerPersonalRecord">();
	}
	static class UPyWidget_CareerPersonalRecord* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_CareerPersonalRecord>();
	}
};
static_assert(alignof(UPyWidget_CareerPersonalRecord) == 0x000008, "Wrong alignment on UPyWidget_CareerPersonalRecord");
static_assert(sizeof(UPyWidget_CareerPersonalRecord) == 0x000920, "Wrong size on UPyWidget_CareerPersonalRecord");
static_assert(offsetof(UPyWidget_CareerPersonalRecord, FadeInAnimInterval) == 0x0005EC, "Member 'UPyWidget_CareerPersonalRecord::FadeInAnimInterval' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord, ScrollListGuideTipsStyle) == 0x0005F0, "Member 'UPyWidget_CareerPersonalRecord::ScrollListGuideTipsStyle' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord, ShowDetailGuideTipsStyle) == 0x000700, "Member 'UPyWidget_CareerPersonalRecord::ShowDetailGuideTipsStyle' has a wrong offset!");
static_assert(offsetof(UPyWidget_CareerPersonalRecord, PlayBackGuideTipsStyle) == 0x000810, "Member 'UPyWidget_CareerPersonalRecord::PlayBackGuideTipsStyle' has a wrong offset!");

// PythonClass PyWidget_CareerPersonalRecord.PyWidget_CareerPersonalRecordItem_Data
// 0x0000 (0x0030 - 0x0030)
class UPyWidget_CareerPersonalRecordItem_Data final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_CareerPersonalRecordItem_Data">();
	}
	static class UPyWidget_CareerPersonalRecordItem_Data* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_CareerPersonalRecordItem_Data>();
	}
};
static_assert(alignof(UPyWidget_CareerPersonalRecordItem_Data) == 0x000008, "Wrong alignment on UPyWidget_CareerPersonalRecordItem_Data");
static_assert(sizeof(UPyWidget_CareerPersonalRecordItem_Data) == 0x000030, "Wrong size on UPyWidget_CareerPersonalRecordItem_Data");

}

