#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Common_Task

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Common_Task.PyWidget_Common_SubTask
// 0x0010 (0x0600 - 0x05F0)
class UPyWidget_Common_SubTask : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E9[0x3];                                      // 0x05E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         OptimalDisplayLength;                              // 0x05EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LimitDisplayLength;                                // 0x05F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FullDisplayLength;                                 // 0x05F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCustomColorPreview;                               // 0x05F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void Destruct();
	void Construct();
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Common_SubTask">();
	}
	static class UPyWidget_Common_SubTask* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Common_SubTask>();
	}
};
static_assert(alignof(UPyWidget_Common_SubTask) == 0x000008, "Wrong alignment on UPyWidget_Common_SubTask");
static_assert(sizeof(UPyWidget_Common_SubTask) == 0x000600, "Wrong size on UPyWidget_Common_SubTask");
static_assert(offsetof(UPyWidget_Common_SubTask, OptimalDisplayLength) == 0x0005EC, "Member 'UPyWidget_Common_SubTask::OptimalDisplayLength' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_SubTask, LimitDisplayLength) == 0x0005F0, "Member 'UPyWidget_Common_SubTask::LimitDisplayLength' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_SubTask, FullDisplayLength) == 0x0005F4, "Member 'UPyWidget_Common_SubTask::FullDisplayLength' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_SubTask, bCustomColorPreview) == 0x0005F8, "Member 'UPyWidget_Common_SubTask::bCustomColorPreview' has a wrong offset!");

// PythonClass PyWidget_Common_Task.PyWidget_Common_Task
// 0x0040 (0x0630 - 0x05F0)
class UPyWidget_Common_Task : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E9[0x3];                                      // 0x05E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         DelayDisplayTime;                                  // 0x05EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OptimalDisplayLength;                              // 0x05F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LimitDisplayLength;                                // 0x05F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FullDisplayLength;                                 // 0x05F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCustomColorPreview;                               // 0x05FC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5FD[0x3];                                      // 0x05FD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CustomColorPreviewText;                            // 0x0600(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class FText                                   CustomColorPreveiwSubText;                         // 0x0618(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void Destruct();
	void Construct();
	void PreConstruct(bool IsDesignTime);
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Common_Task">();
	}
	static class UPyWidget_Common_Task* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Common_Task>();
	}
};
static_assert(alignof(UPyWidget_Common_Task) == 0x000008, "Wrong alignment on UPyWidget_Common_Task");
static_assert(sizeof(UPyWidget_Common_Task) == 0x000630, "Wrong size on UPyWidget_Common_Task");
static_assert(offsetof(UPyWidget_Common_Task, DelayDisplayTime) == 0x0005EC, "Member 'UPyWidget_Common_Task::DelayDisplayTime' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_Task, OptimalDisplayLength) == 0x0005F0, "Member 'UPyWidget_Common_Task::OptimalDisplayLength' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_Task, LimitDisplayLength) == 0x0005F4, "Member 'UPyWidget_Common_Task::LimitDisplayLength' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_Task, FullDisplayLength) == 0x0005F8, "Member 'UPyWidget_Common_Task::FullDisplayLength' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_Task, bCustomColorPreview) == 0x0005FC, "Member 'UPyWidget_Common_Task::bCustomColorPreview' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_Task, CustomColorPreviewText) == 0x000600, "Member 'UPyWidget_Common_Task::CustomColorPreviewText' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_Task, CustomColorPreveiwSubText) == 0x000618, "Member 'UPyWidget_Common_Task::CustomColorPreveiwSubText' has a wrong offset!");

}

