#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_VoiceChatPanel

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"
#include "SlateCore_structs.hpp"
#include "Marvel_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "PyWidget_Common_Button_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_VoiceChatPanel.PyWidget_VoiceStateButton
// 0x0008 (0x0770 - 0x0768)
class UPyWidget_VoiceStateButton : public UPyWidget_CommonButton_WithHoverTips
{
public:
	bool                                          Is_Message;                                        // 0x0768(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_VoiceStateButton">();
	}
	static class UPyWidget_VoiceStateButton* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_VoiceStateButton>();
	}
};
static_assert(alignof(UPyWidget_VoiceStateButton) == 0x000008, "Wrong alignment on UPyWidget_VoiceStateButton");
static_assert(sizeof(UPyWidget_VoiceStateButton) == 0x000770, "Wrong size on UPyWidget_VoiceStateButton");
static_assert(offsetof(UPyWidget_VoiceStateButton, Is_Message) == 0x000768, "Member 'UPyWidget_VoiceStateButton::Is_Message' has a wrong offset!");

// PythonClass PyWidget_VoiceChatPanel.PyWidget_VoiceStateBase
// 0x0000 (0x05F0 - 0x05F0)
class UPyWidget_VoiceStateBase : public UPyMarvelUserWidget
{
public:
	void Construct();
	void Destruct();
	void SetMicrophoneState(int32 MicrophoneState);
	void SetVoiceState(int32 Voice);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_VoiceStateBase">();
	}
	static class UPyWidget_VoiceStateBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_VoiceStateBase>();
	}
};
static_assert(alignof(UPyWidget_VoiceStateBase) == 0x000008, "Wrong alignment on UPyWidget_VoiceStateBase");
static_assert(sizeof(UPyWidget_VoiceStateBase) == 0x0005F0, "Wrong size on UPyWidget_VoiceStateBase");

// PythonClass PyWidget_VoiceChatPanel.PyWidget_VoiceChatPanel
// 0x0008 (0x05F8 - 0x05F0)
class UPyWidget_VoiceChatPanel : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E9[0x7];                                      // 0x05E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UUserWidget>                EntryClass;                                        // 0x05F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_VoiceChatPanel">();
	}
	static class UPyWidget_VoiceChatPanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_VoiceChatPanel>();
	}
};
static_assert(alignof(UPyWidget_VoiceChatPanel) == 0x000008, "Wrong alignment on UPyWidget_VoiceChatPanel");
static_assert(sizeof(UPyWidget_VoiceChatPanel) == 0x0005F8, "Wrong size on UPyWidget_VoiceChatPanel");
static_assert(offsetof(UPyWidget_VoiceChatPanel, EntryClass) == 0x0005F0, "Member 'UPyWidget_VoiceChatPanel::EntryClass' has a wrong offset!");

// PythonClass PyWidget_VoiceChatPanel.PyWidget_VoiceStateImage
// 0x05D0 (0x0BC0 - 0x05F0)
class UPyWidget_VoiceStateImage : public UPyWidget_VoiceStateBase
{
public:
	struct FSlateBrush                            MessageBrush_Enable;                               // 0x05F0(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateBrush                            MessageBrush_Disable;                              // 0x06C0(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateBrush                            MicrophoneBrush_Enable;                            // 0x0790(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateBrush                            MicrophoneBrush_Disable;                           // 0x0860(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateBrush                            VoiceBrush_Speaking;                               // 0x0930(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateBrush                            VoiceBrush_Enable;                                 // 0x0A00(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateBrush                            VoiceBrush_Disable;                                // 0x0AD0(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FLinearColor                           TeamColor;                                         // 0x0BA0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           EnemyColor;                                        // 0x0BB0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void SetMicrophoneState(int32 MicrophoneState);
	void SetVoiceState(int32 Voice);
	void SetIsMicrophone(bool IsMicrophone);
	void SetIconColor(const struct FLinearColor& Color);
	void SetMessageState(int32 State);
	void SetIsMessage(bool Is_Message);
	void OnAnimationFinished(const class UWidgetAnimation* Animation);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_VoiceStateImage">();
	}
	static class UPyWidget_VoiceStateImage* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_VoiceStateImage>();
	}
};
static_assert(alignof(UPyWidget_VoiceStateImage) == 0x000010, "Wrong alignment on UPyWidget_VoiceStateImage");
static_assert(sizeof(UPyWidget_VoiceStateImage) == 0x000BC0, "Wrong size on UPyWidget_VoiceStateImage");
static_assert(offsetof(UPyWidget_VoiceStateImage, MessageBrush_Enable) == 0x0005F0, "Member 'UPyWidget_VoiceStateImage::MessageBrush_Enable' has a wrong offset!");
static_assert(offsetof(UPyWidget_VoiceStateImage, MessageBrush_Disable) == 0x0006C0, "Member 'UPyWidget_VoiceStateImage::MessageBrush_Disable' has a wrong offset!");
static_assert(offsetof(UPyWidget_VoiceStateImage, MicrophoneBrush_Enable) == 0x000790, "Member 'UPyWidget_VoiceStateImage::MicrophoneBrush_Enable' has a wrong offset!");
static_assert(offsetof(UPyWidget_VoiceStateImage, MicrophoneBrush_Disable) == 0x000860, "Member 'UPyWidget_VoiceStateImage::MicrophoneBrush_Disable' has a wrong offset!");
static_assert(offsetof(UPyWidget_VoiceStateImage, VoiceBrush_Speaking) == 0x000930, "Member 'UPyWidget_VoiceStateImage::VoiceBrush_Speaking' has a wrong offset!");
static_assert(offsetof(UPyWidget_VoiceStateImage, VoiceBrush_Enable) == 0x000A00, "Member 'UPyWidget_VoiceStateImage::VoiceBrush_Enable' has a wrong offset!");
static_assert(offsetof(UPyWidget_VoiceStateImage, VoiceBrush_Disable) == 0x000AD0, "Member 'UPyWidget_VoiceStateImage::VoiceBrush_Disable' has a wrong offset!");
static_assert(offsetof(UPyWidget_VoiceStateImage, TeamColor) == 0x000BA0, "Member 'UPyWidget_VoiceStateImage::TeamColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_VoiceStateImage, EnemyColor) == 0x000BB0, "Member 'UPyWidget_VoiceStateImage::EnemyColor' has a wrong offset!");

// PythonClass PyWidget_VoiceChatPanel.PyWidget_VoiceReportButton
// 0x0000 (0x0768 - 0x0768)
class UPyWidget_VoiceReportButton : public UPyWidget_CommonButton_WithHoverTips
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_VoiceReportButton">();
	}
	static class UPyWidget_VoiceReportButton* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_VoiceReportButton>();
	}
};
static_assert(alignof(UPyWidget_VoiceReportButton) == 0x000008, "Wrong alignment on UPyWidget_VoiceReportButton");
static_assert(sizeof(UPyWidget_VoiceReportButton) == 0x000768, "Wrong size on UPyWidget_VoiceReportButton");

// PythonClass PyWidget_VoiceChatPanel.PyWidget_BattleVoice_PlayerUnit
// 0x0018 (0x0608 - 0x05F0)
class UPyWidget_BattleVoice_PlayerUnit : public UPyMarvelUserWidget
{
public:
	bool                                          bCustomColorPreview;                               // 0x05E9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          PreviewIsSelf;                                     // 0x05EA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5EB[0x1];                                      // 0x05EB(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         PreviewHeroID;                                     // 0x05EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FText                                   PreviewHeroName;                                   // 0x05F0(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_BattleVoice_PlayerUnit">();
	}
	static class UPyWidget_BattleVoice_PlayerUnit* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_BattleVoice_PlayerUnit>();
	}
};
static_assert(alignof(UPyWidget_BattleVoice_PlayerUnit) == 0x000008, "Wrong alignment on UPyWidget_BattleVoice_PlayerUnit");
static_assert(sizeof(UPyWidget_BattleVoice_PlayerUnit) == 0x000608, "Wrong size on UPyWidget_BattleVoice_PlayerUnit");
static_assert(offsetof(UPyWidget_BattleVoice_PlayerUnit, bCustomColorPreview) == 0x0005E9, "Member 'UPyWidget_BattleVoice_PlayerUnit::bCustomColorPreview' has a wrong offset!");
static_assert(offsetof(UPyWidget_BattleVoice_PlayerUnit, PreviewIsSelf) == 0x0005EA, "Member 'UPyWidget_BattleVoice_PlayerUnit::PreviewIsSelf' has a wrong offset!");
static_assert(offsetof(UPyWidget_BattleVoice_PlayerUnit, PreviewHeroID) == 0x0005EC, "Member 'UPyWidget_BattleVoice_PlayerUnit::PreviewHeroID' has a wrong offset!");
static_assert(offsetof(UPyWidget_BattleVoice_PlayerUnit, PreviewHeroName) == 0x0005F0, "Member 'UPyWidget_BattleVoice_PlayerUnit::PreviewHeroName' has a wrong offset!");

// PythonClass PyWidget_VoiceChatPanel.PyWidget_CombatAudioControlPanel
// 0x0130 (0x0720 - 0x05F0)
class UPyWidget_CombatAudioControlPanel : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E9[0x3];                                      // 0x05E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMargin                                VoiceEntryPadding;                                 // 0x05EC(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_5FC[0x4];                                      // 0x05FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UUserWidget>                EntryClass;                                        // 0x0600(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ProtectTime;                                       // 0x0608(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_60C[0x4];                                      // 0x060C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGuideTipsStyle                        PCScrollGuideTipsStyle;                            // 0x0610(0x0110)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void OnCascadingVisibleChanged(bool Visible);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_CombatAudioControlPanel">();
	}
	static class UPyWidget_CombatAudioControlPanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_CombatAudioControlPanel>();
	}
};
static_assert(alignof(UPyWidget_CombatAudioControlPanel) == 0x000008, "Wrong alignment on UPyWidget_CombatAudioControlPanel");
static_assert(sizeof(UPyWidget_CombatAudioControlPanel) == 0x000720, "Wrong size on UPyWidget_CombatAudioControlPanel");
static_assert(offsetof(UPyWidget_CombatAudioControlPanel, VoiceEntryPadding) == 0x0005EC, "Member 'UPyWidget_CombatAudioControlPanel::VoiceEntryPadding' has a wrong offset!");
static_assert(offsetof(UPyWidget_CombatAudioControlPanel, EntryClass) == 0x000600, "Member 'UPyWidget_CombatAudioControlPanel::EntryClass' has a wrong offset!");
static_assert(offsetof(UPyWidget_CombatAudioControlPanel, ProtectTime) == 0x000608, "Member 'UPyWidget_CombatAudioControlPanel::ProtectTime' has a wrong offset!");
static_assert(offsetof(UPyWidget_CombatAudioControlPanel, PCScrollGuideTipsStyle) == 0x000610, "Member 'UPyWidget_CombatAudioControlPanel::PCScrollGuideTipsStyle' has a wrong offset!");

// PythonClass PyWidget_VoiceChatPanel.PyWidget_CombatAudioControlEntry
// 0x0860 (0x0E50 - 0x05F0)
class UPyWidget_CombatAudioControlEntry : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E9[0x3];                                      // 0x05E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           TeamColor;                                         // 0x05EC(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           EnemyColor;                                        // 0x05FC(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSlateColor                            SelfNameColor;                                     // 0x060C(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateColor                            TeamNameColor;                                     // 0x0620(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	uint8                                         Pad_634[0xC];                                      // 0x0634(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FButtonStyle                           BtnTeamBgStyle;                                    // 0x0640(0x0400)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FButtonStyle                           BtnEnemyBgStyle;                                   // 0x0A40(0x0400)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class UTexture2D*                             ImgPortraitBgTeam;                                 // 0x0E40(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             ImgPortraitBgEnemy;                                // 0x0E48(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void OnPictureLoadCompleted(class UTexture2D* Picture);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_CombatAudioControlEntry">();
	}
	static class UPyWidget_CombatAudioControlEntry* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_CombatAudioControlEntry>();
	}
};
static_assert(alignof(UPyWidget_CombatAudioControlEntry) == 0x000010, "Wrong alignment on UPyWidget_CombatAudioControlEntry");
static_assert(sizeof(UPyWidget_CombatAudioControlEntry) == 0x000E50, "Wrong size on UPyWidget_CombatAudioControlEntry");
static_assert(offsetof(UPyWidget_CombatAudioControlEntry, TeamColor) == 0x0005EC, "Member 'UPyWidget_CombatAudioControlEntry::TeamColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_CombatAudioControlEntry, EnemyColor) == 0x0005FC, "Member 'UPyWidget_CombatAudioControlEntry::EnemyColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_CombatAudioControlEntry, SelfNameColor) == 0x00060C, "Member 'UPyWidget_CombatAudioControlEntry::SelfNameColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_CombatAudioControlEntry, TeamNameColor) == 0x000620, "Member 'UPyWidget_CombatAudioControlEntry::TeamNameColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_CombatAudioControlEntry, BtnTeamBgStyle) == 0x000640, "Member 'UPyWidget_CombatAudioControlEntry::BtnTeamBgStyle' has a wrong offset!");
static_assert(offsetof(UPyWidget_CombatAudioControlEntry, BtnEnemyBgStyle) == 0x000A40, "Member 'UPyWidget_CombatAudioControlEntry::BtnEnemyBgStyle' has a wrong offset!");
static_assert(offsetof(UPyWidget_CombatAudioControlEntry, ImgPortraitBgTeam) == 0x000E40, "Member 'UPyWidget_CombatAudioControlEntry::ImgPortraitBgTeam' has a wrong offset!");
static_assert(offsetof(UPyWidget_CombatAudioControlEntry, ImgPortraitBgEnemy) == 0x000E48, "Member 'UPyWidget_CombatAudioControlEntry::ImgPortraitBgEnemy' has a wrong offset!");

// PythonClass PyWidget_VoiceChatPanel.PyWidget_VoiceStateIcon
// 0x0340 (0x0930 - 0x05F0)
class UPyWidget_VoiceStateIcon final : public UPyWidget_VoiceStateBase
{
public:
	struct FSlateBrush                            MicrophoneBrush_Enable;                            // 0x05F0(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateBrush                            MicrophoneBrush_Disable;                           // 0x06C0(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateBrush                            VoiceBrush_Enable;                                 // 0x0790(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateBrush                            VoiceBrush_Disable;                                // 0x0860(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	void SetMicrophoneState(int32 MicrophoneState);
	void SetVoiceState(int32 Voice);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_VoiceStateIcon">();
	}
	static class UPyWidget_VoiceStateIcon* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_VoiceStateIcon>();
	}
};
static_assert(alignof(UPyWidget_VoiceStateIcon) == 0x000010, "Wrong alignment on UPyWidget_VoiceStateIcon");
static_assert(sizeof(UPyWidget_VoiceStateIcon) == 0x000930, "Wrong size on UPyWidget_VoiceStateIcon");
static_assert(offsetof(UPyWidget_VoiceStateIcon, MicrophoneBrush_Enable) == 0x0005F0, "Member 'UPyWidget_VoiceStateIcon::MicrophoneBrush_Enable' has a wrong offset!");
static_assert(offsetof(UPyWidget_VoiceStateIcon, MicrophoneBrush_Disable) == 0x0006C0, "Member 'UPyWidget_VoiceStateIcon::MicrophoneBrush_Disable' has a wrong offset!");
static_assert(offsetof(UPyWidget_VoiceStateIcon, VoiceBrush_Enable) == 0x000790, "Member 'UPyWidget_VoiceStateIcon::VoiceBrush_Enable' has a wrong offset!");
static_assert(offsetof(UPyWidget_VoiceStateIcon, VoiceBrush_Disable) == 0x000860, "Member 'UPyWidget_VoiceStateIcon::VoiceBrush_Disable' has a wrong offset!");

}

