#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_LeagueSchedule_Main

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "PyWidget_ModuleMainPanel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_LeagueSchedule_Main.PyWidget_LeagueSchedule_Main
// 0x0010 (0x0628 - 0x0618)
class UPyWidget_LeagueSchedule_Main final : public UPyWidget_ModuleMainPanel
{
public:
	uint8                                         Pad_611[0x7];                                      // 0x0611(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FGuideTipsStyle>                LocateGuideList;                                   // 0x0618(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_LeagueSchedule_Main">();
	}
	static class UPyWidget_LeagueSchedule_Main* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_LeagueSchedule_Main>();
	}
};
static_assert(alignof(UPyWidget_LeagueSchedule_Main) == 0x000008, "Wrong alignment on UPyWidget_LeagueSchedule_Main");
static_assert(sizeof(UPyWidget_LeagueSchedule_Main) == 0x000628, "Wrong size on UPyWidget_LeagueSchedule_Main");
static_assert(offsetof(UPyWidget_LeagueSchedule_Main, LocateGuideList) == 0x000618, "Member 'UPyWidget_LeagueSchedule_Main::LocateGuideList' has a wrong offset!");

}

