#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Ability_V5

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Ability_V5.PyWidget_AbilityCommon_V5
// 0x0000 (0x05A8 - 0x05A8)
class UPyWidget_AbilityCommon_V5 : public UWidget_AbilityCommon
{
public:
	class UAbilityCommonExtraWidgets* GetWidgetsByStyles_V5(const struct FWidgetStyle_AbilityCommon_V5& InStyle);
	void SetVisibleImmediately(bool Invisible);
	void Reset();
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_AbilityCommon_V5">();
	}
	static class UPyWidget_AbilityCommon_V5* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_AbilityCommon_V5>();
	}
};
static_assert(alignof(UPyWidget_AbilityCommon_V5) == 0x000008, "Wrong alignment on UPyWidget_AbilityCommon_V5");
static_assert(sizeof(UPyWidget_AbilityCommon_V5) == 0x0005A8, "Wrong size on UPyWidget_AbilityCommon_V5");

}

