#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SM_PracticeRangeBuilding001A

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SM_PracticeRangeBuilding001A.SM_PracticeRangeBuilding001A_C
// 0x0018 (0x04A8 - 0x0490)
class ASM_PracticeRangeBuilding001A_C final : public AActor
{
public:
	class UStaticMeshComponent*                   SM_PracticeRangeBuilding001Ac;                     // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_PracticeRangeBuilding001Ab;                     // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        SM_PracticeRangeBuilding001A;                      // 0x04A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SM_PracticeRangeBuilding001A_C">();
	}
	static class ASM_PracticeRangeBuilding001A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASM_PracticeRangeBuilding001A_C>();
	}
};
////static_assert(alignof(ASM_PracticeRangeBuilding001A_C) == 0x000008, "Wrong alignment on ASM_PracticeRangeBuilding001A_C");
////static_assert(sizeof(ASM_PracticeRangeBuilding001A_C) == 0x0004A8, "Wrong size on ASM_PracticeRangeBuilding001A_C");
////static_assert(offsetof(ASM_PracticeRangeBuilding001A_C, SM_PracticeRangeBuilding001Ac) == 0x000490, "Member 'ASM_PracticeRangeBuilding001A_C::SM_PracticeRangeBuilding001Ac' has a wrong offset!");
////static_assert(offsetof(ASM_PracticeRangeBuilding001A_C, SM_PracticeRangeBuilding001Ab) == 0x000498, "Member 'ASM_PracticeRangeBuilding001A_C::SM_PracticeRangeBuilding001Ab' has a wrong offset!");
////static_assert(offsetof(ASM_PracticeRangeBuilding001A_C, SM_PracticeRangeBuilding001A) == 0x0004A0, "Member 'ASM_PracticeRangeBuilding001A_C::SM_PracticeRangeBuilding001A' has a wrong offset!");

}

