#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SM_WakandaH01Prop002A2_Blueprint

#include "Basic.hpp"

#include "MarvelLevel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SM_WakandaH01Prop002A2_Blueprint.SM_WakandaH01Prop002A2_Blueprint_C
// 0x0030 (0x04D8 - 0x04A8)
class ASM_WakandaH01Prop002A2_Blueprint_C final : public AEnvironmentStaticActor
{
public:
	class UStaticMeshComponent*                   SM_WakandaH01Prop002A2_StaticMeshComponent0;       // 0x04A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_WakandaH01Prop004A3_StaticMeshComponent0;       // 0x04B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_WakandaH01Prop001A4_StaticMeshComponent0;       // 0x04B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_WakandaH01Prop003A3_StaticMeshComponent0;       // 0x04C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_WakandaH01Component015Ae6_StaticMeshComponent0; // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Interactor_NoColliisionPart;                       // 0x04D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SM_WakandaH01Prop002A2_Blueprint_C">();
	}
	static class ASM_WakandaH01Prop002A2_Blueprint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASM_WakandaH01Prop002A2_Blueprint_C>();
	}
};
////static_assert(alignof(ASM_WakandaH01Prop002A2_Blueprint_C) == 0x000008, "Wrong alignment on ASM_WakandaH01Prop002A2_Blueprint_C");
////static_assert(sizeof(ASM_WakandaH01Prop002A2_Blueprint_C) == 0x0004D8, "Wrong size on ASM_WakandaH01Prop002A2_Blueprint_C");
////static_assert(offsetof(ASM_WakandaH01Prop002A2_Blueprint_C, SM_WakandaH01Prop002A2_StaticMeshComponent0) == 0x0004A8, "Member 'ASM_WakandaH01Prop002A2_Blueprint_C::SM_WakandaH01Prop002A2_StaticMeshComponent0' has a wrong offset!");
////static_assert(offsetof(ASM_WakandaH01Prop002A2_Blueprint_C, SM_WakandaH01Prop004A3_StaticMeshComponent0) == 0x0004B0, "Member 'ASM_WakandaH01Prop002A2_Blueprint_C::SM_WakandaH01Prop004A3_StaticMeshComponent0' has a wrong offset!");
////static_assert(offsetof(ASM_WakandaH01Prop002A2_Blueprint_C, SM_WakandaH01Prop001A4_StaticMeshComponent0) == 0x0004B8, "Member 'ASM_WakandaH01Prop002A2_Blueprint_C::SM_WakandaH01Prop001A4_StaticMeshComponent0' has a wrong offset!");
////static_assert(offsetof(ASM_WakandaH01Prop002A2_Blueprint_C, SM_WakandaH01Prop003A3_StaticMeshComponent0) == 0x0004C0, "Member 'ASM_WakandaH01Prop002A2_Blueprint_C::SM_WakandaH01Prop003A3_StaticMeshComponent0' has a wrong offset!");
////static_assert(offsetof(ASM_WakandaH01Prop002A2_Blueprint_C, SM_WakandaH01Component015Ae6_StaticMeshComponent0) == 0x0004C8, "Member 'ASM_WakandaH01Prop002A2_Blueprint_C::SM_WakandaH01Component015Ae6_StaticMeshComponent0' has a wrong offset!");
////static_assert(offsetof(ASM_WakandaH01Prop002A2_Blueprint_C, Interactor_NoColliisionPart) == 0x0004D0, "Member 'ASM_WakandaH01Prop002A2_Blueprint_C::Interactor_NoColliisionPart' has a wrong offset!");

}

