#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Summoned_20000102_BP

#include "Basic.hpp"

#include "Summoned_20000102_BP_classes.hpp"
#include "Summoned_20000102_BP_parameters.hpp"


namespace SDK
{

// Function Summoned_20000102_BP.Summoned_20000102_BP_C.SetNavEffectBox
// (BlueprintCallable, BlueprintEvent)

void ASummoned_20000102_BP_C::SetNavEffectBox()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Summoned_20000102_BP_C", "SetNavEffectBox");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Summoned_20000102_BP.Summoned_20000102_BP_C.ExecuteUbergraph_Summoned_20000102_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASummoned_20000102_BP_C::ExecuteUbergraph_Summoned_20000102_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Summoned_20000102_BP_C", "ExecuteUbergraph_Summoned_20000102_BP");

	Params::Summoned_20000102_BP_C_ExecuteUbergraph_Summoned_20000102_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

