#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ui_controller_reload

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass ui_controller_reload.UIController_Reload
// 0x0000 (0x0030 - 0x0030)
class UUIController_Reload final : public UUIC_Reload
{
public:
	void OnAmmoAttributeChanged(class AActor* SourceActor, const struct FAttributeModifierHandle& Parameter);
	void AddAbility(class UMarvelGameplayAbility* InAbility);
	void SetTargetCharacter(class AMarvelBaseCharacter* InTargetCharacter);
	void Destruct();
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UIController_Reload">();
	}
	static class UUIController_Reload* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIController_Reload>();
	}
};
//static_assert(alignof(UUIController_Reload) == 0x000008, "Wrong alignment on UUIController_Reload");
//static_assert(sizeof(UUIController_Reload) == 0x000030, "Wrong size on UUIController_Reload");

}

