#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIController_201_BP

#include "Basic.hpp"

#include "PyAbility_201_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass UIController_201_BP.UIController_201_BP_C
// 0x0000 (0x0D68 - 0x0D68)
class UUIController_201_BP_C final : public UPyUIController_201
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UIController_201_BP_C">();
	}
	static class UUIController_201_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIController_201_BP_C>();
	}
};
//static_assert(alignof(UUIController_201_BP_C) == 0x000008, "Wrong alignment on UUIController_201_BP_C");
//static_assert(sizeof(UUIController_201_BP_C) == 0x000D68, "Wrong size on UUIController_201_BP_C");

}

