#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Ability_Relation

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PyWidget_AbilityStatus_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Ability_Relation.WBP_Ability_Relation_C
// 0x0018 (0x03D0 - 0x03B8)
class UWBP_Ability_Relation_C final : public UPyWidget_AbilityRelationIcon
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UMarvelImage*                           Image_plus;                                        // 0x03C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Image_reduce;                                      // 0x03C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Ability_Relation(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Ability_Relation_C">();
	}
	static class UWBP_Ability_Relation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Ability_Relation_C>();
	}
};
//static_assert(alignof(UWBP_Ability_Relation_C) == 0x000008, "Wrong alignment on UWBP_Ability_Relation_C");
//static_assert(sizeof(UWBP_Ability_Relation_C) == 0x0003D0, "Wrong size on UWBP_Ability_Relation_C");
//static_assert(offsetof(UWBP_Ability_Relation_C, UberGraphFrame) == 0x0003B8, "Member 'UWBP_Ability_Relation_C::UberGraphFrame' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_Relation_C, Image_plus) == 0x0003C0, "Member 'UWBP_Ability_Relation_C::Image_plus' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_Relation_C, Image_reduce) == 0x0003C8, "Member 'UWBP_Ability_Relation_C::Image_reduce' has a wrong offset!");

}

