#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Common_ActionTips

#include "Basic.hpp"

#include "PyWidget_Common_ActionTips_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Common_ActionTips.WBP_Common_ActionTips_C
// 0x0008 (0x05F8 - 0x05F0)
class UWBP_Common_ActionTips_C final : public UPyWidget_Common_ActionTips
{
public:
	class UWBP_Beginner_ActionTips_C*             WBP_ActionTip_Left;                                // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Common_ActionTips_C">();
	}
	static class UWBP_Common_ActionTips_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Common_ActionTips_C>();
	}
};
//static_assert(alignof(UWBP_Common_ActionTips_C) == 0x000008, "Wrong alignment on UWBP_Common_ActionTips_C");
//static_assert(sizeof(UWBP_Common_ActionTips_C) == 0x0005F8, "Wrong size on UWBP_Common_ActionTips_C");
//static_assert(offsetof(UWBP_Common_ActionTips_C, WBP_ActionTip_Left) == 0x0005F0, "Member 'UWBP_Common_ActionTips_C::WBP_ActionTip_Left' has a wrong offset!");

}

