#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Ability_WeaponUnit_V7

#include "Basic.hpp"

#include "PyWidget_WeaponStatus_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Ability_WeaponUnit_V7.WBP_Ability_WeaponUnit_V7_C
// 0x0070 (0x0670 - 0x0600)
class UWBP_Ability_WeaponUnit_V7_C final : public UPyWidget_WeaponIcon
{
public:
	class UWidgetAnimation*                       Anim_Faction;                                      // 0x0600(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       AnimStates_WeaponMode;                             // 0x0608(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anim_FoldWeapon;                                   // 0x0610(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anim_Sign_Normal;                                  // 0x0618(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWBP_Ability_WeaponAmmoUnit_C*          Ammo;                                              // 0x0620(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Sign_Normal;                                   // 0x0628(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Sign_NormalShadow;                             // 0x0630(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Weapon;                                        // 0x0638(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Common_KeyWidget_C*                Key;                                               // 0x0640(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPyBattleScaleBox*                      ScaleBox_WeaponAmmo;                               // 0x0648(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPyBattleScaleBox*                      ScaleBox_WeaponIocn;                               // 0x0650(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPyBattleScaleBox*                      ScaleBox_WeaponSign;                               // 0x0658(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_Weapon;                                    // 0x0660(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          _____;                                             // 0x0668(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Ability_WeaponUnit_V7_C">();
	}
	static class UWBP_Ability_WeaponUnit_V7_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Ability_WeaponUnit_V7_C>();
	}
};
//static_assert(alignof(UWBP_Ability_WeaponUnit_V7_C) == 0x000008, "Wrong alignment on UWBP_Ability_WeaponUnit_V7_C");
//static_assert(sizeof(UWBP_Ability_WeaponUnit_V7_C) == 0x000670, "Wrong size on UWBP_Ability_WeaponUnit_V7_C");
//static_assert(offsetof(UWBP_Ability_WeaponUnit_V7_C, Anim_Faction) == 0x000600, "Member 'UWBP_Ability_WeaponUnit_V7_C::Anim_Faction' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_WeaponUnit_V7_C, AnimStates_WeaponMode) == 0x000608, "Member 'UWBP_Ability_WeaponUnit_V7_C::AnimStates_WeaponMode' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_WeaponUnit_V7_C, Anim_FoldWeapon) == 0x000610, "Member 'UWBP_Ability_WeaponUnit_V7_C::Anim_FoldWeapon' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_WeaponUnit_V7_C, Anim_Sign_Normal) == 0x000618, "Member 'UWBP_Ability_WeaponUnit_V7_C::Anim_Sign_Normal' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_WeaponUnit_V7_C, Ammo) == 0x000620, "Member 'UWBP_Ability_WeaponUnit_V7_C::Ammo' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_WeaponUnit_V7_C, Img_Sign_Normal) == 0x000628, "Member 'UWBP_Ability_WeaponUnit_V7_C::Img_Sign_Normal' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_WeaponUnit_V7_C, Img_Sign_NormalShadow) == 0x000630, "Member 'UWBP_Ability_WeaponUnit_V7_C::Img_Sign_NormalShadow' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_WeaponUnit_V7_C, Img_Weapon) == 0x000638, "Member 'UWBP_Ability_WeaponUnit_V7_C::Img_Weapon' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_WeaponUnit_V7_C, Key) == 0x000640, "Member 'UWBP_Ability_WeaponUnit_V7_C::Key' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_WeaponUnit_V7_C, ScaleBox_WeaponAmmo) == 0x000648, "Member 'UWBP_Ability_WeaponUnit_V7_C::ScaleBox_WeaponAmmo' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_WeaponUnit_V7_C, ScaleBox_WeaponIocn) == 0x000650, "Member 'UWBP_Ability_WeaponUnit_V7_C::ScaleBox_WeaponIocn' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_WeaponUnit_V7_C, ScaleBox_WeaponSign) == 0x000658, "Member 'UWBP_Ability_WeaponUnit_V7_C::ScaleBox_WeaponSign' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_WeaponUnit_V7_C, SizeBox_Weapon) == 0x000660, "Member 'UWBP_Ability_WeaponUnit_V7_C::SizeBox_Weapon' has a wrong offset!");
//static_assert(offsetof(UWBP_Ability_WeaponUnit_V7_C, _____) == 0x000668, "Member 'UWBP_Ability_WeaponUnit_V7_C::_____' has a wrong offset!");

}

