#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CollaborativeAbility_TipsHeroHead_Sub

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_CollaborativeAbility_TipsHeroHead_Sub.WBP_CollaborativeAbility_TipsHeroHead_Sub_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_CollaborativeAbility_TipsHeroHead_Sub_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
//static_assert(alignof(WBP_CollaborativeAbility_TipsHeroHead_Sub_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_CollaborativeAbility_TipsHeroHead_Sub_C_PreConstruct");
//static_assert(sizeof(WBP_CollaborativeAbility_TipsHeroHead_Sub_C_PreConstruct) == 0x000001, "Wrong size on WBP_CollaborativeAbility_TipsHeroHead_Sub_C_PreConstruct");
//static_assert(offsetof(WBP_CollaborativeAbility_TipsHeroHead_Sub_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_CollaborativeAbility_TipsHeroHead_Sub_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_CollaborativeAbility_TipsHeroHead_Sub.WBP_CollaborativeAbility_TipsHeroHead_Sub_C.ExecuteUbergraph_WBP_CollaborativeAbility_TipsHeroHead_Sub
// 0x0010 (0x0010 - 0x0000)
struct WBP_CollaborativeAbility_TipsHeroHead_Sub_C_ExecuteUbergraph_WBP_CollaborativeAbility_TipsHeroHead_Sub final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             K2Node_Select_Default;                             // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
//static_assert(alignof(WBP_CollaborativeAbility_TipsHeroHead_Sub_C_ExecuteUbergraph_WBP_CollaborativeAbility_TipsHeroHead_Sub) == 0x000008, "Wrong alignment on WBP_CollaborativeAbility_TipsHeroHead_Sub_C_ExecuteUbergraph_WBP_CollaborativeAbility_TipsHeroHead_Sub");
//static_assert(sizeof(WBP_CollaborativeAbility_TipsHeroHead_Sub_C_ExecuteUbergraph_WBP_CollaborativeAbility_TipsHeroHead_Sub) == 0x000010, "Wrong size on WBP_CollaborativeAbility_TipsHeroHead_Sub_C_ExecuteUbergraph_WBP_CollaborativeAbility_TipsHeroHead_Sub");
//static_assert(offsetof(WBP_CollaborativeAbility_TipsHeroHead_Sub_C_ExecuteUbergraph_WBP_CollaborativeAbility_TipsHeroHead_Sub, EntryPoint) == 0x000000, "Member 'WBP_CollaborativeAbility_TipsHeroHead_Sub_C_ExecuteUbergraph_WBP_CollaborativeAbility_TipsHeroHead_Sub::EntryPoint' has a wrong offset!");
//static_assert(offsetof(WBP_CollaborativeAbility_TipsHeroHead_Sub_C_ExecuteUbergraph_WBP_CollaborativeAbility_TipsHeroHead_Sub, Temp_bool_Variable) == 0x000004, "Member 'WBP_CollaborativeAbility_TipsHeroHead_Sub_C_ExecuteUbergraph_WBP_CollaborativeAbility_TipsHeroHead_Sub::Temp_bool_Variable' has a wrong offset!");
//static_assert(offsetof(WBP_CollaborativeAbility_TipsHeroHead_Sub_C_ExecuteUbergraph_WBP_CollaborativeAbility_TipsHeroHead_Sub, K2Node_Event_IsDesignTime) == 0x000005, "Member 'WBP_CollaborativeAbility_TipsHeroHead_Sub_C_ExecuteUbergraph_WBP_CollaborativeAbility_TipsHeroHead_Sub::K2Node_Event_IsDesignTime' has a wrong offset!");
//static_assert(offsetof(WBP_CollaborativeAbility_TipsHeroHead_Sub_C_ExecuteUbergraph_WBP_CollaborativeAbility_TipsHeroHead_Sub, K2Node_Select_Default) == 0x000008, "Member 'WBP_CollaborativeAbility_TipsHeroHead_Sub_C_ExecuteUbergraph_WBP_CollaborativeAbility_TipsHeroHead_Sub::K2Node_Select_Default' has a wrong offset!");

}

